/*
 * Universal Video Player v2.9
 *
 * Copyright 2014-2018, LambertGroup
 *
*/


(function(d){function Y(a,b,e){e.css({background:a.playlistRecordBgOffColor});a.playlistRecordShowTitle?d(".title",e).css({color:a.playlistRecordTitleOffColor}):d(".title",e).css({display:"none"});a.playlistRecordShowDesc?d(".reg",e).css({color:a.playlistRecordDescOffColor}):d(".reg",e).css({display:"none"});b=e.find("img:first");a.playlistRecordShowImg?b.css({opacity:a.playlistRecordBgOffImgOpacity/100,filter:"alpha(opacity="+a.playlistRecordBgOffImgOpacity+")"}):b.css({display:"none"})}function Z(a,
b,e){e.css({background:a.playlistRecordBgOnColor});d(".title",e).css({color:a.playlistRecordTitleOnColor});d(".reg",e).css({color:a.playlistRecordDescOnColor});e.find("img:first").css({opacity:a.playlistRecordBgOnImgOpacity/100,filter:"alpha(opacity="+a.playlistRecordBgOnImgOpacity+")"})}function X(a,b,e,g,h,f,n,p,q,k,l,m,r,z,y,w,x){var t=!0,B="next",D=e.shuffle;-1==a&&(B="previous");b.thumbsClicked&&(D=!1);if(!e.loop&&b.current_img_no+a>=b.selectedCateg_total_images||!e.loop&&0>b.current_img_no+
a||b.categsAreListed)t=!1;t&&(clearInterval(b.youTubeInterval),clearInterval(b.vimeoInterval),clearInterval(b.selfHostedInterval),Y(e,b,d(b.thumbsHolder_Thumbs[b.current_img_no])),xa(b,e,g,y),b.is_vast?(d("#"+b.html5_video_id).css({"z-index":-1,width:0,height:0}),document.getElementById(b.html5_video_id).pause(),x.css({display:"none"})):(a=B,D?(D=Math.floor(Math.random()*(b.selectedCateg_total_images-1)),b.current_img_no=D!=b.current_img_no?D:Math.floor(Math.random()*(b.selectedCateg_total_images-
1))):"next"==a?b.current_img_no==b.selectedCateg_total_images-1?b.current_img_no=0:b.current_img_no++:0>b.current_img_no-1?b.current_img_no=b.selectedCateg_total_images-1:b.current_img_no--,b.origID=d("div[rel='"+b.current_img_no+"']").attr("data-origID"),b.previousOrigID=b.origID),b.currentImg=b.playlist_arr[b.origID],f.html(b.playlist_arr[b.origID].title),b.thumbsClicked=!1,Z(e,b,d(b.thumbsHolder_Thumbs[b.current_img_no])),da(0,h,e,b),ka(b,e,l),(void 0!=b.currentImg.youtube&&""!=b.currentImg.youtube||
void 0!=b.currentImg.vimeo&&""!=b.currentImg.vimeo||void 0!=b.currentImg.selfhostedMP4&&""!=b.currentImg.selfhostedMP4)&&ya(b,e,g,n,p,q,k,l,m,r,z,y,w,f,x,h))}function da(a,b,e,g){if(g.selectedCateg_total_images>e.numberOfThumbsPerScreen){e=(g.thumbsHolder_Thumb.height()+g.thumbMarginTop)*(g.selectedCateg_total_images-e.numberOfThumbsPerScreen);var h=0;b.stop(!0,!0);d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()});a&&!g.isCarouselScrolling?(g.isCarouselScrolling=
!0,1>=a&&(a=0),h=parseInt(e*(a-100)/100,10),0<h&&(h=0),b.animate({top:h+"px"},600,"easeOutQuad",function(){g.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})})):g.isCarouselScrolling||(g.isCarouselScrolling=!0,b.css("opacity","0.5"),h=parseInt(-(g.thumbsHolder_Thumb.height()+g.thumbMarginTop)*g.current_img_no,10),Math.abs(h)>e&&(h=-e),g.universal_video_player_sliderVertical.slider("value",100+parseInt(100*h/e,10)),b.animate({opacity:1,top:h+
"px"},500,"easeOutCubic",function(){g.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function ra(a,b,e,g,h,f,n,p,q,k){if(a.categsAreListed||""==a.thumbsHolder_Thumbs)k.click();else{k=0;b.origWidth!=b.width&&(k=2*b.borderWidth);p=d(".thumbsHolder_ThumbOFF .title",e);q=d(".thumbsHolder_ThumbOFF .reg",e);n=d(".thumbsHolder_ThumbOFF .padding",e);a.thumbsHolder_Thumbs.css({height:parseInt(h.height()/b.numberOfThumbsPerScreen,10)+"px"});n.css({"padding-left":parseInt(b.origthumbLeftPadding/
(b.origWidth/(b.width-k)),10)+"px","padding-right":parseInt(b.origthumbRightPadding/(b.origWidth/(b.width-k)),10)+"px","padding-top":parseInt(b.origthumbTopPadding/(b.origWidth/(b.width-k)),10)+"px","padding-bottom":parseInt(b.origthumbBottomPadding/(b.origWidth/(b.width-k)),10)+"px"});h="px";-1!=p.css("font-size").lastIndexOf("em")&&(h="em");n="px";-1!=p.css("line-height").lastIndexOf("em")&&(n="em");p.css({"font-size":parseInt(b.origthumbTitleFont/(b.origWidth/(b.width-k)),10)+h,"line-height":parseInt(b.origthumbTitleLineHeight/
(b.origWidth/(b.width-k)),10)+n});h="px";-1!=q.css("font-size").lastIndexOf("em")&&(h="em");n="px";-1!=q.css("line-height").lastIndexOf("em")&&(n="em");q.css({"font-size":parseInt(b.origthumbRegFont/(b.origWidth/(b.width-k)),10)+h,"line-height":parseInt(b.origthumbRegLineHeight/(b.origWidth/(b.width-k)),10)+n});b.playlistRecordShowImg&&(e=d(".thumbsHolder_ThumbOFF",e).find("img:first"),!b.playlistRecordShowTitle&&!b.playlistRecordShowDesc||b.origWidth==b.width?b.playlistRecordShowTitle||b.playlistRecordShowDesc?
e.css({width:parseInt(b.origThumbImgW/(b.origWidth/b.width),10)+"px",height:parseInt(b.origThumbImgH/(b.origWidth/b.width),10)+"px"}):e.css({width:parseInt(b.origThumbImgW/(b.origWidth/b.width),10)+1+"px",height:a.thumbsHolder_Thumbs.height()+"px"}):e.css({width:parseInt(b.origThumbImgW/(b.origWidth/(b.width-42)),10)+"px",height:parseInt(b.origThumbImgH/(b.origWidth/(b.width-42)),10)+"px"}));var l=0,m=0;a.categsAreListed||(a.thumbMarginTop=Math.floor((f.height()-a.thumbsHolder_Thumb.height()*b.numberOfThumbsPerScreen)/
(b.numberOfThumbsPerScreen-1)));thumb_i=0;g.children().each(function(){thumb_i++;theThumb=d(this);m=theThumb.height();1>=thumb_i?(l=Math.floor((f.height()-(a.thumbMarginTop+theThumb.height())*(b.numberOfThumbsPerScreen-1)-theThumb.height())/2),1<=l&&(l=0),theThumb.css("margin-top",l+"px"),theThumb.height(m)):theThumb.css("margin-top",a.thumbMarginTop+"px")})}}function la(a,b,e,g){d(".fullscreenVimeoButton",b).css({right:"82px"});374>=g&&d(".fullscreenVimeoButton",b).css({right:"37px"});305>=g&&d(".fullscreenVimeoButton",
b).css({right:"5px"})}function ma(a,b,e,g,h,f,n,p,q,k,l,m,t,z,y,w,x,A,B,D,u,M,H,Q,P,N,I,J,E,F,G,C,za){if(!a.videoIsFullScreen)ea(),e=0,responsiveWidth=g.parent().parent().parent().width(),responsiveHeight=g.parent().parent().parent().height(),b.responsiveRelativeToBrowser&&(responsiveWidth=d(window).width(),responsiveHeight=d(window).height()),b.width100Proc&&(b.width=responsiveWidth),b.height100Proc&&(b.height=responsiveHeight),b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:
b.width100Proc||(b.width=b.origWidth),b.height100Proc||(b.height=b.width/a.playerRatio),b.width=parseInt(b.width,10),b.height=parseInt(b.height,10),n.width(b.width),n.height(b.height),a.new_width=parseInt(b.width-b.playlistWidth/(b.origWidth/b.width)-3*b.borderWidth,10),a.new_height=b.height-2*b.borderWidth,b.playlistVisible||(a.new_width=parseInt(b.width-0-2*b.borderWidth,10)),f.width(a.new_width),f.height(a.new_height),f.css({left:b.borderWidth+"px",top:b.borderWidth+"px"}),d(".lbg_player",f).width(a.new_width),
d(".lbg_player",f).height(a.new_height),d(".lbg_vimeo_player",f).width(a.new_width),d(".lbg_vimeo_player",f).height(a.new_height),la(a,f,k,a.new_width),q.width(b.playlistWidth/(b.origWidth/b.width)),q.height(a.new_height),k.width(b.playlistWidth/(b.origWidth/b.width)),k.height(a.new_height),k.css({top:0,right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),p.width(b.playlistWidth/(b.origWidth/b.width)),p.css("top","0px"),a.selectedCateg_total_images>b.numberOfThumbsPerScreen&&(0>=
b.borderWidth&&(e=a.universal_video_player_sliderVertical.width()/2),a.universal_video_player_sliderVertical.height(k.height()-15),a.universal_video_player_sliderVertical.css({display:"block",left:Math.floor(b.width-2*b.borderWidth+(b.borderWidth-a.universal_video_player_sliderVertical.width())/2)-e+"px"})),b.showCategs&&(z.css({width:b.playlistWidth/(b.origWidth/b.width)+"px",right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),y.css({"background-position":b.playlistWidth/(b.origWidth/
b.width)-9+"px 50%"})),g="block",b.playlistVisible||(g="none"),b.showSearch&&(b.width<=a.minimalWidthSearch&&(g="none"),w.css({width:b.playlistWidth/(b.origWidth/b.width)+"px",top:3+(b.height-2*b.borderWidth)+"px",right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px",display:g}),x.css({width:parseInt(b.playlistWidth/(b.origWidth/b.width),10)-100+"px"})),b.showLogo&&(w=d(".yourLogo",f).find("img:first"),w.css({"max-width":parseInt(100*b.width/b.origWidth,10)+"%"}),g="block",b.width<=
a.minimalWidthSearch&&(g="none"),d(".yourLogo",f).css({display:g})),b.playlistVisible?(b.showNextPrevBut&&(I.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),J.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-I.width()-a.buttonsDistanceSeekBar)+"px"})),b.showShuffleBut&&E.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-I.width()-J.width()-a.totalButtonsDistanceSeekBar)+"px"})):(b.showNextPrevBut&&(I.css({right:0}),J.css({right:I.width()+
a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&E.css({right:I.width()+J.width()+a.totalButtonsDistanceSeekBar+"px"})),b.width<=a.minimalWidthInfo?V(a,b,f,A,B,D,u,M,H,Q,P,N,!1,!1):b.width<=a.minimalWidthDownload?V(a,b,f,A,B,D,u,M,H,Q,P,N,!1,!0):V(a,b,f,A,B,D,u,M,H,Q,P,N,!0,!0),S(a,a.origID)&&fa(a,b,f,F,G,C,"none"),ra(a,b,f,p,q,k,l,m,t,z);else if(-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))N.click(),ma(a,
b,e,g,h,f,n,p,q,k,l,m,t,z,y,w,x,A,B,D,u,M,H,Q,P,N,I,J,E,F,G,C,za);da(0,p,b,a)}function ea(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,d=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=d.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,d=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=d.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function sa(a,b,d){var e=b.playlist_arr[b.origID].selfhostedWEBM,h=navigator.userAgent.toLowerCase();
if(-1!=h.indexOf("chrome")||-1!=h.indexOf("msie")||-1!=h.indexOf("safari")||-1!=h.indexOf("android"))e=b.playlist_arr[b.origID].selfhostedMP4;if(-1!=h.indexOf("ipad")||-1!=h.indexOf("iphone")||-1!=h.indexOf("ipod")||-1!=h.indexOf("webos"))e=b.playlist_arr[b.origID].selfhostedMP4;-1!=h.indexOf("android")&&(e=b.playlist_arr[b.origID].selfhostedMP4);-1!=a&&(e=b.playlist_arr[b.origID].selfhostedMP4);-1!=h.indexOf("opera")&&(e=b.playlist_arr[b.origID].selfhostedWEBM,""!=na(d)&&(e=b.playlist_arr[b.origID].selfhostedMP4));
-1!=h.indexOf("opr/")&&(e=b.playlist_arr[b.origID].selfhostedWEBM,""!=na(d)&&(e=b.playlist_arr[b.origID].selfhostedMP4));if(-1!=h.indexOf("firefox")||-1!=h.indexOf("mozzila"))e=b.playlist_arr[b.origID].selfhostedWEBM,""!=na(d)&&(e=b.playlist_arr[b.origID].selfhostedMP4);return e}function O(a,b){var d=!1;void 0!=a.playlist_arr[b].youtube&&""!=a.playlist_arr[b].youtube&&a.haveYouTube&&(d=!0);return d}function S(a,b){var d=!1;void 0!=a.playlist_arr[b].vimeo&&""!=a.playlist_arr[b].vimeo&&a.haveVimeo&&
(d=!0);return d}function U(a,b){var d=!1;void 0!=a.playlist_arr[b].selfhostedMP4&&""!=a.playlist_arr[b].selfhostedMP4&&a.haveSelfHosted&&(d=!0);return d}function R(a){var b=10>Math.floor(a/60)?"0"+Math.floor(a/60):Math.floor(a/60);return b+":"+(10>Math.floor(a-60*b)?"0"+Math.floor(a-60*b):Math.floor(a-60*b))}function ta(a,b,e,g,h,f,n,p,q,k){var l=a.playlist_arr[a.origID].startpoint;""!=a.playlist_arr[a.origID].startpoint&&(l=oa(a.playlist_arr[a.origID].startpoint));var m=oa(a.playlist_arr[a.origID].endpoint);
""!=a.playlist_arr[a.origID].endpoint&&(m=oa(a.playlist_arr[a.origID].endpoint));clearInterval(a.youTubeInterval);clearInterval(a.vimeoInterval);clearInterval(a.selfHostedInterval);a.totalTime=0;a.curTime=0;b.isBufferInitialized&&(g.progressbar("destroy"),b.isBufferInitialized=!1);b.isSeekBarInitialized&&(h.slider("destroy"),b.isSeekBarInitialized=!1);a.bufferedTime=0;g.css({background:b.bufferEmptyColor});S(a,a.origID)||(g.progressbar({value:0,complete:function(){a.is_buffer_complete=!0},create:function(a,
d){b.isBufferInitialized=!0}}),d(".ui-widget-header",g).css({background:b.bufferFullColor}),g.css({display:"block"}),h.css({display:"block"}),f.css({display:"block"}));S(a,a.origID)&&a.videoIsFullScreen&&(g.css({display:"none"}),h.css({display:"none"}),f.css({display:"none"}));O(a,a.origID)&&(a.youTubeInterval=setInterval(function(){if(!a.is_vast){var f=!0;-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")||a.youtubeWasStarted==
YT.PlayerState.PLAYING||(f=!1);0!=a.isYouTubeReady&&(!b.isSeekBarInitialized&&0<a.player.getDuration()&&f&&!a.is_vast&&(h.slider({value:0,step:.5,orientation:"horizontal",range:"min",max:a.player.getDuration(),slide:function(){a.is_seeking=!0;d("iframe",e).css({"pointer-events":"none"})},stop:function(b,f){a.is_seeking=!1;d("iframe",e).css({"pointer-events":"auto"});a.player.seekTo(f.value)},create:function(a,d){b.isSeekBarInitialized=!0}}),d(".ui-slider-range",h).css({background:b.seekbarColor})),
n.html(R(a.player.getDuration())+"/"+R(a.player.getCurrentTime())),l>a.player.getCurrentTime()&&0!=a.player.getCurrentTime()&&""!=l&&a.player.seekTo(l),a.player.getCurrentTime()>l&&""!=l&&pa(a,e),m<a.player.getCurrentTime()&&0!=a.player.getCurrentTime()&&""!=m&&k.click(),a.is_buffer_complete||(a.bufferedTime=100*a.player.getVideoLoadedFraction(),g.progressbar({value:a.bufferedTime})),!a.is_seeking&&b.isSeekBarInitialized&&h.slider("value",a.player.getCurrentTime()))}},500));S(a,a.origID)&&(a.vimeoInterval=
setInterval(function(){a.is_vast||(n.html(R(a.totalTime)+"/"+R(a.curTime)),0<a.totalTime||a.vimeo_player.getDuration().then(function(b){a.totalTime=b})["catch"](function(a){}),l>a.curTime&&0!=a.curTime&&""!=l&&0<a.totalTime&&a.vimeo_player.setCurrentTime(l).then(function(a){})["catch"](function(a){}),a.curTime>l&&""!=l&&0<a.totalTime&&pa(a,e),m<a.curTime&&0!=a.curTime&&""!=m&&0<a.totalTime&&(a.curTime=0,k.click()),a.vimeo_player.getCurrentTime().then(function(b){a.curTime=b;0<now&&a.curTime++})["catch"](function(a){}))},
500));if(U(a,a.origID)){var t=parseInt(g.width(),10);a.selfHostedInterval=setInterval(function(){a.is_vast||(a.curTime=document.getElementById(a.html5_video_id).currentTime,a.totalTime=document.getElementById(a.html5_video_id).duration,!b.isSeekBarInitialized&&0<a.totalTime&&(h.slider({value:0,step:.5,orientation:"horizontal",range:"min",max:a.totalTime,slide:function(){a.is_seeking=!0},stop:function(b,d){a.is_seeking=!1;document.getElementById(a.html5_video_id).currentTime=d.value},create:function(a,
d){b.isSeekBarInitialized=!0}}),d(".ui-slider-range",h).css({background:b.seekbarColor})),n.html(R(a.totalTime)+"/"+R(a.curTime)),l>a.curTime&&0!=a.curTime&&""!=l&&0<a.totalTime&&(document.getElementById(a.html5_video_id).currentTime=l),a.curTime>l&&""!=l&&0<a.totalTime&&pa(a,e),m<a.curTime&&0!=a.curTime&&""!=m&&0<a.totalTime&&k.click(),a.bufferedTime=document.getElementById(a.html5_video_id).buffered,a.is_buffer_complete||(a.bufferedTime=a.bufferedTime.length?parseFloat(document.getElementById(a.html5_video_id).buffered.end(0)):
document.getElementById(a.html5_video_id).buffered,0<a.bufferedTime&&g.progressbar({value:a.bufferedTime*t/a.totalTime})),!a.is_seeking&&b.isSeekBarInitialized&&h.slider("value",a.curTime))},500)}}function fa(a,b,e,g,h,f,n){f=0;var p=d(".showHidePlaylistBut",e).width()+a.buttonsDistance,q=n,k="none";"none"==n&&(k="block");O(a,a.origID)&&(q="none");d(".firstset_controls",e).css("display",n);g.css("display",n);h.css("display",n);"block"==n&&(f=a.showPlaylistButOrigLeft,p=a.fullscreenButOrigLeft);d(".largePlayButton",
e).css({display:q});d(".fullscreenVimeoButton",e).css({display:k});b.showPlaylistBut&&d(".showHidePlaylistBut",e).css({left:f+"px"});b.showFullscreenBut&&d(".fullscreenBut",e).css({left:p+"px",display:n})}function Aa(a,b){O(a,a.previousOrigID)&&d(".lbg_player",b).css({"z-index":-1,display:"none",visibility:"hidden"});S(a,a.previousOrigID)&&d(".lbg_vimeo_player",b).css({"z-index":-1,display:"none",visibility:"hidden"});U(a,a.previousOrigID)&&d("#"+a.html5_video_id).css({"z-index":-1,display:"none",
visibility:"hidden"});d("iframe",b).css({display:"none",visibility:"hidden"})}function pa(a,b){O(a,a.origID)&&d(".lbg_player",b).css({"z-index":4,display:"block",visibility:"visible"});S(a,a.origID)&&d(".lbg_vimeo_player",b).css({"z-index":4,display:"block",visibility:"visible"});U(a,a.origID)&&d("#"+a.html5_video_id).css({"z-index":4,display:"block",visibility:"visible"});d("iframe",b).css({display:"block",visibility:"visible"})}function xa(a,b,e,g){O(a,a.previousOrigID)&&(a.player.stopVideo(),d(".lbg_player",
e).css({"z-index":-1}));S(a,a.previousOrigID)&&(a.vimeo_player.pause(),d(".lbg_vimeo_player",e).css({"z-index":-1}),a.vimeo_player.getVolume().then(function(g){b.initialVolume=g;d(".volumeSlider",e).slider("value",b.initialVolume);O(a,a.origID)&&a.player.setVolume(100*b.initialVolume);U(a,a.origID)&&(document.getElementById(a.html5_video_id).volume=b.initialVolume)})["catch"](function(a){}));U(a,a.previousOrigID)&&(document.getElementById(a.html5_video_id).pause(),d("#"+a.html5_video_id).css({"z-index":-1,
width:0,height:0}))}function ya(a,b,e,g,h,f,n,p,q,k,l,m,t,z,y,w){b.autoPlayFirstVideo=!0;n.hasClass("pauseBut")||n.addClass("pauseBut");if(void 0==a.playlist_arr[a.origID].vast||""==a.playlist_arr[a.origID].vast||a.is_vast){a.is_vast=!1;O(a,a.origID)&&(a.youtubeWasStarted=-1,e.css("background","#000000"),-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?(a.player.cueVideoById(a.playlist_arr[a.origID].youtube),
n.removeClass("pauseBut")):a.player.loadVideoById(a.playlist_arr[a.origID].youtube,0,b.suggestedQuality),a.player.setVolume(100*b.initialVolume),d(".lbg_player",e).css({"z-index":4}),fa(a,b,e,g,h,q,"block"),b.googleTrakingOn&&ga("send","event",a.googleYouTubeCateg,"Play","Title: "+a.playlist_arr[a.origID].title+"  ---  ID: "+a.playlist_arr[a.origID].youtube));S(a,a.origID)&&(e.css("background","#000000"),a.curTime=0,a.vimeo_player.unload(),a.vimeo_player.loadVideo(a.playlist_arr[a.origID].vimeo).then(function(d){a.vimeo_player.setVolume(b.initialVolume);
b.loop&&-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&a.vimeo_player.play()})["catch"](function(a){}),d(".lbg_vimeo_player",e).css({"z-index":4}),fa(a,b,e,g,h,q,"none"),p.css({display:"none"}),b.googleTrakingOn&&ga("send","event",a.googleVimeoCateg,"Play","Title: "+a.playlist_arr[a.origID].title+"  ---  ID: "+a.playlist_arr[a.origID].vimeo));if(U(a,a.origID)){var x=ea();e.css("background","#000000");var A=
new Date;document.getElementById(a.html5_video_id).src=sa(x,a,a.html5_video_id)+"?time="+A.getTime();document.getElementById(a.html5_video_id).load();a.curTime=0;d("#"+a.html5_video_id).css({"z-index":4,width:"100%",height:"100%"});document.getElementById(a.html5_video_id).volume=b.initialVolume;document.getElementById(a.html5_video_id).play();fa(a,b,e,g,h,q,"block");b.googleTrakingOn&&ga("send","event",a.googleSelfHostedCateg,"Play","Title: "+a.playlist_arr[a.origID].title+"  ---  ID: "+a.playlist_arr[a.origID].selfhostedMP4)}ta(a,
b,e,g,h,q,f,p,m,t)}else a.is_vast=!0,d.get(b.pathToAjaxFiles+"vast.php",{the_file:a.playlist_arr[a.origID].vast},function(d){ua(d,a,b,z,e,h,g,f,y,n,w,p,q,k,l,m,t)});a.videoIsFullScreen&&b.showPlaylistBut&&(k.css({display:"none"}),l.css({left:parseInt(l.css("left").substr(0,l.css("left").lastIndexOf("px")),10)-k.width()-a.buttonsDistance+"px"}));""!=a.playlist_arr[a.origID].startpoint&&Aa(a,e)}function va(a,b){a=String(a);var d="";if(a.length>b){a=a.substring(0,b);var g=a.split(" ");var h=a.substring(b-
2,b-1);""!=h&&(g.pop(),d="...");a=g.join(" ")}return a+d}function wa(a,b,e,g,h){e.css("top","0px");var f=0;b.isPlaylistSliderInitialized&&a.universal_video_player_sliderVertical.slider("destroy");b.isPlaylistSliderInitialized=!1;a.selectedCateg_total_images>b.numberOfThumbsPerScreen&&(a.universal_video_player_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(d,f){da(f.value,e,b,a)}}),b.isPlaylistSliderInitialized=!0,0>=b.borderWidth&&(f=a.universal_video_player_sliderVertical.width()/
2),a.universal_video_player_sliderVertical.height(h.height()-15),a.universal_video_player_sliderVertical.css({display:"block",left:Math.floor(b.width-2*b.borderWidth+(b.borderWidth-a.universal_video_player_sliderVertical.width())/2)-f+"px"}),d(".ui-slider-handle",a.universal_video_player_sliderVertical).css({"background-color":b.playlistScrollerBgColorOFF}),d(".ui-slider-handle",a.universal_video_player_sliderVertical).mouseover(function(){d(this).css({"background-color":b.playlistScrollerBgColorON})}),
d(".ui-slider-handle",a.universal_video_player_sliderVertical).mouseout(function(){d(this).css({"background-color":b.playlistScrollerBgColorOFF})}),g.mousewheel(function(d,f,g,h){d.preventDefault();d=a.universal_video_player_sliderVertical.slider("value");if(1<parseInt(d,10)&&-1==parseInt(f,10)||100>parseInt(d,10)&&1==parseInt(f,10))d+=f,a.universal_video_player_sliderVertical.slider("value",d),da(d,e,b,a)}))}function Ba(a,b,e,g,h,f,n,p,q,k,l,m,r,z,y,w,x,A,B,D,u,M,H,Q,P,N,I,J,E,F,G,C){g.stop(!0,!0);
a.isCarouselScrolling=!1;g.stop().animate({left:-1*f.width()+"px"},600,"easeOutQuad",function(){g.html("");for(var t=0;t<a.category_arr.length;t++)a.thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF categUnit" rel="'+t+'"><div class="padding"><span class="title">'+a.category_arr[t]+"</span></div></div>"),g.append(a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_Thumb.height()+1)*t+"px",background:b.categoryRecordBgOffColor,"border-bottom-color":b.categoryRecordBottomBorderOffColor,
color:b.categoryRecordTextOffColor}),a.category_arr[t]==a.selectedCateg&&(a.current_img_no=t,a.thumbsHolder_Thumb.css({background:b.categoryRecordBgOnColor,"border-bottom-color":b.categoryRecordBottomBorderOnColor,color:b.categoryRecordTextOnColor}));a.thumbMarginTop=0;b.numberOfThumbsPerScreen=Math.floor((b.height-2*b.borderWidth)/(a.thumbsHolder_Thumb.height()+1))-1;a.selectedCateg_total_images=a.numberOfCategories;a.categsAreListed=!0;a.thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",e);wa(a,b,
g,f,h);a.thumbsHolder_Thumbs.click(function(){if(!a.is_vast){var t=d(this).attr("rel");a.selectedCateg=a.category_arr[t];ver_ie=ea();p.html(a.selectedCateg);ha(a,b,e,g,h,f,n,q,k,l,m,r,z,y,w,x,A,B,D,u,M,H,Q,P,N,I,J,E,ver_ie,F,G,C)}});a.thumbsHolder_Thumbs.mouseover(function(){d(this).css({background:b.categoryRecordBgOnColor,"border-bottom-color":b.categoryRecordBottomBorderOnColor,color:b.categoryRecordTextOnColor})});a.thumbsHolder_Thumbs.mouseout(function(){var f=d(this),e=f.attr("rel");a.current_img_no!=
e&&f.css({background:b.categoryRecordBgOffColor,"border-bottom-color":b.categoryRecordBottomBorderOffColor,color:b.categoryRecordTextOffColor})});g.stop().animate({left:"0px"},400,"easeOutQuad",function(){})})}function ha(a,b,e,g,h,f,n,p,q,k,l,m,t,z,y,w,x,A,B,D,u,M,H,Q,P,N,I,J,E,F,G,C){g.stop(!0,!0);a.isCarouselScrolling=!1;a.categsAreListed=!1;l=k="";var O=!1;p=500;a.is_very_first&&(p=1);""!=a.search_val&&(p=1);g.css({left:-1*f.width()+"px"});g.html("");for(var K=a.selectedCateg_total_images=0;K<
a.playlist_arr.length;K++){O=!1;if(""!=a.search_val){if(k=a.playlist_arr[K].title.toLowerCase(),l=a.playlist_arr[K].desc.toLowerCase(),-1!=k.indexOf(a.search_val)||-1!=l.indexOf(a.search_val))O=!0}else-1!=a.playlist_arr[K].category.indexOf(a.selectedCateg+";")&&(O=!0);O&&(a.selectedCateg_total_images++,k=a.playlist_arr[K]["bottom-thumb"],thumbUnit="",b.playlistRecordShowImg&&(thumbUnit='<img src="'+k+'">'),a.thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF" rel="'+(a.selectedCateg_total_images-
1)+'" data-origID="'+K+'"><div class="padding">'+thumbUnit+'<span class="title">'+va(a.playlist_arr[K].title,b.playlistRecordTitleLimit)+'</span><span class="reg">'+va(a.playlist_arr[K].desc,b.playlistRecordDescLimit)+"</span></div></div>"),g.append(a.thumbsHolder_Thumb),Y(b,a,a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({height:b.playlistRecordHeight+"px"}),d(".padding",a.thumbsHolder_Thumb).css({padding:b.playlistRecordPadding+"px"}),0==b.origThumbW&&(0==b.numberOfThumbsPerScreen&&(b.numberOfThumbsPerScreen=
Math.floor((b.origHeight-2*b.borderWidth)/a.thumbsHolder_Thumb.height())),b.origNumberOfThumbsPerScreen=b.numberOfThumbsPerScreen,b.origThumbW=a.thumbsHolder_Thumb.width(),b.origThumbH=a.thumbsHolder_Thumb.height(),q=d(".thumbsHolder_ThumbOFF .padding",e),b.origthumbLeftPadding=q.css("padding-left").substr(0,q.css("padding-left").lastIndexOf("px")),b.origthumbRightPadding=q.css("padding-right").substr(0,q.css("padding-left").lastIndexOf("px")),b.origthumbTopPadding=q.css("padding-top").substr(0,q.css("padding-left").lastIndexOf("px")),
b.origthumbBottomPadding=q.css("padding-bottom").substr(0,q.css("padding-left").lastIndexOf("px")),a.thumbMarginTop=Math.floor((h.height()-a.thumbsHolder_Thumb.height()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),a.origThumbMarginTop=a.thumbMarginTop,k=d(".thumbsHolder_ThumbOFF .title",e),l=d(".thumbsHolder_ThumbOFF .reg",e),k.css({"font-size":b.playlistTitleFontSize+"px","line-height":b.playlistTitleLineHeight+"px"}),l.css({"font-size":b.playlistDescFontSize+"px","line-height":b.playlistDescLineHeight+
"px"}),-1!=k.css("font-size").lastIndexOf("px")?b.origthumbTitleFont=k.css("font-size").substr(0,k.css("font-size").lastIndexOf("px")):-1!=k.css("font-size").lastIndexOf("em")&&(b.origthumbTitleFont=k.css("font-size").substr(0,k.css("font-size").lastIndexOf("em"))),-1!=k.css("line-height").lastIndexOf("px")?b.origthumbTitleLineHeight=k.css("line-height").substr(0,k.css("line-height").lastIndexOf("px")):-1!=k.css("line-height").lastIndexOf("em")&&(b.origthumbTitleLineHeight=k.css("line-height").substr(0,
k.css("line-height").lastIndexOf("em"))),-1!=l.css("font-size").lastIndexOf("px")?b.origthumbRegFont=l.css("font-size").substr(0,l.css("font-size").lastIndexOf("px")):-1!=l.css("font-size").lastIndexOf("em")&&(b.origthumbRegFont=l.css("font-size").substr(0,l.css("font-size").lastIndexOf("em"))),-1!=l.css("line-height").lastIndexOf("px")?b.origthumbRegLineHeight=l.css("line-height").substr(0,l.css("line-height").lastIndexOf("px")):-1!=l.css("line-height").lastIndexOf("em")&&(b.origthumbRegLineHeight=
l.css("line-height").substr(0,l.css("line-height").lastIndexOf("em")))))}0!=b.origNumberOfThumbsPerScreen&&(b.numberOfThumbsPerScreen=b.origNumberOfThumbsPerScreen,a.thumbMarginTop=a.origThumbMarginTop);wa(a,b,g,f,h);a.thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",e);a.thumbsHolder_Thumbs.removeClass("categUnit");k=d(".thumbsHolder_ThumbOFF .title",e);l=d(".thumbsHolder_ThumbOFF .reg",e);a.thumbsHolder_Thumbs.click(function(){if(!a.is_vast){var c=d(this).attr("rel");Y(b,a,d(a.thumbsHolder_Thumbs[a.current_img_no]));
a.thumbsClicked=!0;a.current_img_no=c-1;X(1,a,b,e,g,m,t,z,y,w,x,A,B,D,u,F,G)}});a.thumbsHolder_Thumbs.mouseenter(function(){var c=d(this);c.attr("rel");Z(b,a,c)});a.thumbsHolder_Thumbs.mouseleave(function(){var c=d(this),f=c.attr("rel");a.current_img_no!=f&&Y(b,a,c)});ra(a,b,e,g,f,h,q,k,l,n);a.current_img_no=0;a.is_very_first&&(a.current_img_no=b.firstVideo,b.firstVideo>a.selectedCateg_total_images&&(a.current_img_no=a.selectedCateg_total_images),0>b.firstVideo&&(a.current_img_no=0));b.shuffle&&(a.current_img_no=
Math.floor(Math.random()*a.selectedCateg_total_images));Z(b,a,d(a.thumbsHolder_Thumbs[a.current_img_no]));a.origID=d("div[rel='"+a.current_img_no+"']").attr("data-origID");m.html(a.playlist_arr[a.origID].title);a.currentImg=a.playlist_arr[a.origID];g.stop().animate({left:"0px"},p,"easeOutQuad",function(){b.shuffle&&da(0,g,b,a)});if(a.is_very_first){void 0!=a.playlist_arr[a.origID].vast&&""!=a.playlist_arr[a.origID].vast&&(a.is_vast=!0);if(a.haveYouTube){var S=function(c){a.youtubeWasStarted!=YT.PlayerState.PLAYING&&
(a.youtubeWasStarted=c.data);c.data==YT.PlayerState.ENDED&&X(1,a,b,e,g,m,t,z,y,w,x,A,B,D,u,F,G);c.data==YT.PlayerState.PAUSED&&w.removeClass("pauseBut");c.data==YT.PlayerState.PLAYING&&w.addClass("pauseBut")},U=function(c){-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&(a.player.setVolume(100*b.initialVolume),b.autoPlayFirstVideo?void 0==a.currentImg.youtube||""==a.currentImg.youtube||a.is_vast||(c.target.playVideo(),
w.hasClass("pauseBut")||w.addClass("pauseBut")):(c.target.pauseVideo(),a.player.cueVideoById(a.currentImg.youtube)));a.isYouTubeReady=!0};h=document.createElement("script");h.src=b.youtubeJsUrl;f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(h,f);window.onYouTubeIframeAPIReady=function(){void 0!=a.currentImg.youtube&&""!=a.currentImg.youtube?(a.player=new YT.Player(M,{width:a.new_width,height:b.height-2*b.borderWidth,videoId:a.currentImg.youtube,playerVars:{rel:0,wmode:"opaque",
controls:0,showinfo:0,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,fs:0,disablekb:1},events:{onReady:U,onStateChange:S}}),d(".lbg_player",e).css({"z-index":4})):a.player=new YT.Player(M,{width:"100%",height:"100%",videoId:"xoORbLlFsis",playerVars:{rel:0,wmode:"opaque",controls:0,showinfo:0,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,fs:0,disablekb:1},events:{onReady:U,onStateChange:S}})}}if(a.haveVimeo){var c=function(c){X(1,a,b,e,g,m,t,z,y,w,x,A,B,D,u,F,G)};void 0!=a.currentImg.vimeo&&
""!=a.currentImg.vimeo?(d(".lbg_vimeo_player",e).html('<iframe id="'+u+'" src="//player.vimeo.com/video/'+a.currentImg.vimeo+"?player_id="+u+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'),d(".lbg_vimeo_player",e).css({"z-index":4})):d(".lbg_vimeo_player",e).html('<iframe id="'+u+'" src="//player.vimeo.com/video/257707848?player_id='+u+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');
a.vimeo_iframe=d("#"+u)[0];a.vimeo_player=new Vimeo.Player(a.vimeo_iframe);a.vimeo_player.ready().then(function(){a.vimeo_player.setVolume(b.initialVolume);b.autoPlayFirstVideo?void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo&&-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&(a.is_vast||a.vimeo_player.play()):a.vimeo_player.pause();a.vimeo_player.on("ended",c)})}a.haveSelfHosted&&(h="",b.autoPlayFirstVideo&&
(h=' autoplay="autoplay"'),-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?b.autoPlayOnMobile&&(h=" muted playsinline",C.addClass("volumeButtonMute")):(0===b.initialVolume&&(h+=' muted="muted"',C.addClass("volumeButtonMute")),-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&b.autoPlayFirstVideo&&
(h+=' muted="muted"',C.addClass("volumeButtonMute")),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(b.autoPlay=!1))),C=d('<video id="'+a.html5_video_id+'" width="100%" height="100%" preload="auto"'+h+"></video>"),e.append(C),d("#"+a.html5_video_id).css({"z-index":-1,width:0,height:0,top:0,left:0,position:"absolute",background:"#000000"}),document.getElementById(a.html5_video_id).volume=b.initialVolume,void 0==a.currentImg.selfhostedMP4||
""==a.currentImg.selfhostedMP4||a.is_vast||(document.getElementById(a.html5_video_id).src=sa(E,a,a.html5_video_id),document.getElementById(a.html5_video_id).load(),d("#"+a.html5_video_id).css({"z-index":4,width:"100%",height:"100%"}),b.autoPlayFirstVideo&&(document.getElementById(a.html5_video_id).play(),-1==r.indexOf("ipad")&&-1==r.indexOf("iphone")&&-1==r.indexOf("ipod")&&-1==r.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&(w.hasClass("pauseBut")||w.addClass("pauseBut")))),document.getElementById(a.html5_video_id).addEventListener("ended",
function(c){X(1,a,b,e,g,m,t,z,y,w,x,A,B,D,u,F,G)},!1));void 0!=a.playlist_arr[a.origID].vast&&""!=a.playlist_arr[a.origID].vast&&(a.is_vast=!0,d.get(b.pathToAjaxFiles+"vast.php",{the_file:a.playlist_arr[a.origID].vast},function(c){ua(c,a,b,m,e,z,t,y,G,w,g,x,A,B,D,u,F)}));b.googleTrakingOn&&(ga("create",b.googleTrakingCode,"auto"),C=E="",void 0!=a.currentImg.youtube&&""!=a.currentImg.youtube&&(E=a.currentImg.youtube,C=a.googleYouTubeCateg),void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo&&(E=a.currentImg.vimeo,
C=a.googleVimeoCateg),void 0!=a.currentImg.selfhostedMP4&&""!=a.currentImg.selfhostedMP4&&(E=a.currentImg.selfhostedMP4,C=a.googleSelfHostedCateg),ga("send","event",C,"Play","Title: "+a.currentImg.title+"  ---  ID: "+E));ta(a,b,e,t,z,A,y,x,u,F);A.css({left:0,height:b.borderWidth+"px",bottom:-1*b.borderWidth+"px"});V(a,b,e,H,w,Q,P,N,I,J,B,D,!0,!0);void 0!=a.currentImg.vimeo&&""!=a.currentImg.vimeo&&fa(a,b,e,t,z,A,"none")}a.is_very_first&&(a.is_very_first=!1,a.previousOrigID=a.origID)}function V(a,
b,d,g,h,f,n,p,q,k,l,m,t,r){a.totalButtonsDistance=0;b.showRewindBut?(g.css({left:0,bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):g.css({display:"none",width:0,height:0,padding:0,margin:0});b.showPlayBut?(h.css({left:g.width()+a.totalButtonsDistance+"px",bottom:"0px","background-color":b.playButColorOff}),a.totalButtonsDistance+=a.buttonsDistance):h.css({display:"none",width:0,height:0,padding:0,margin:0});b.showVolumeBut?(f.css({left:g.width()+h.width()+a.totalButtonsDistance+"px",bottom:"0px"}),
a.totalButtonsDistance+=a.buttonsDistance):f.css({display:"none",width:0,height:0,padding:0,margin:0});b.showFacebookBut?(n.css({left:g.width()+h.width()+f.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):n.css({display:"none",width:0,height:0,padding:0,margin:0});b.showTwitterBut?(p.css({left:g.width()+h.width()+f.width()+n.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):p.css({display:"none",width:0,height:0,
padding:0,margin:0});b.showInfoBut&&r?(q.css({display:"block",width:a.origInfoWidth+"px",height:a.origInfoHeight+"px",left:g.width()+h.width()+f.width()+n.width()+p.width()+a.totalButtonsDistance+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):q.css({display:"none",width:0,height:0,padding:0,margin:0});b.showDownloadBut&&t?(k.css({display:"block",width:a.origDownloadWidth+"px",height:a.origDownloadHeight+"px",left:g.width()+h.width()+f.width()+n.width()+p.width()+q.width()+a.totalButtonsDistance+
"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):k.css({display:"none",width:0,height:0,padding:0,margin:0});b.showPlaylistBut?(a.showPlaylistButOrigLeft=g.width()+h.width()+f.width()+n.width()+p.width()+q.width()+k.width()+a.totalButtonsDistance,l.css({left:a.showPlaylistButOrigLeft+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):l.css({display:"none",width:0,height:0,padding:0,margin:0});b.showFullscreenBut?(a.fullscreenButOrigLeft=g.width()+h.width()+f.width()+n.width()+
p.width()+q.width()+k.width()+l.width()+a.totalButtonsDistance,m.css({left:a.fullscreenButOrigLeft+"px",bottom:"0px"}),a.totalButtonsDistance+=a.buttonsDistance):m.css({display:"none",width:0,height:0,padding:0,margin:0})}function qa(a,b,e,g,h,f,n,p,q,k,l,m,t,r,y,w){if(a.videoIsFullScreen){d("body").css("margin-top",a.origBodyTopMargin);d("body").css("margin-right",a.origBodyRightMargin);d("body").css("margin-bottom",a.origBodyBottomMargin);d("body").css("margin-left",a.origBodyLeftMargin);d("body").css("overflow",
a.origBodyOverflow);d("html").css("overflow",a.origHtmlOverflow);a.videoIsFullScreen=!1;e.css("position",a.containerOrigPosition);e.css("z-index",a.containerOrigZindex);f.css({display:"block"});S(a,a.origID)||(g.css({display:"block"}),h.css({display:"block"}));if(b.playlistVisible){a.new_width=parseInt(b.width-b.playlistWidth/(b.origWidth/b.width)-3*b.borderWidth,10);var x="block";b.showNextPrevBut&&(k.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width))+"px"}),l.css({right:-1*(b.borderWidth+
b.playlistWidth/(b.origWidth/b.width)-k.width()-a.buttonsDistanceSeekBar)+"px"}));b.showShuffleBut&&m.css({right:-1*(b.borderWidth+b.playlistWidth/(b.origWidth/b.width)-k.width()-l.width()-a.totalButtonsDistanceSeekBar)+"px"})}else a.new_width=parseInt(b.width-2*b.borderWidth,10),x="none",b.showNextPrevBut&&(k.css({right:0}),l.css({right:k.width()+a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&m.css({right:k.width()+l.width()+a.totalButtonsDistanceSeekBar+"px"});a.new_height=parseInt(b.height-
2*b.borderWidth,10);n.css({display:x});b.showCategs&&p.css({display:x});b.showSearch&&(q.css({display:x}),b.width<=a.minimalWidthSearch&&q.css({display:"none"}));b.isPlaylistSliderInitialized&&b.playlistVisible&&a.universal_video_player_sliderVertical.css({visibility:"visible"});b.showInfoBut&&t.css({bottom:0});b.showPlaylistBut&&(r.css({display:"block"}),y.css({left:parseInt(y.css("left").substr(0,y.css("left").lastIndexOf("px")),10)+r.width()+a.buttonsDistance+"px"}));e.width(a.new_width);e.height(a.new_height);
e.css({left:b.borderWidth+"px",top:b.borderWidth+"px"});f.css({left:0,bottom:-1*b.borderWidth+"px",background:"none"});g.css({bottom:0});h.css({bottom:0});w.css({bottom:"30px"})}else d("body").css("margin",0),d("body").css("overflow","hidden"),d("html").css("overflow","hidden"),e.css("position","fixed"),e.css("z-index",999990),a.new_width=window.innerWidth,a.new_height=window.innerHeight,a.videoIsFullScreen=!0,S(a,a.origID)&&(g.css({display:"none"}),h.css({display:"none"}),f.css({display:"none"})),
n.css({display:"none"}),b.showCategs&&p.css({display:"none"}),b.showSearch&&q.css({display:"none"}),b.isPlaylistSliderInitialized&&a.universal_video_player_sliderVertical.css({visibility:"hidden"}),b.showNextPrevBut&&(k.css({right:0}),l.css({right:k.width()+a.buttonsDistanceSeekBar+"px"})),b.showShuffleBut&&m.css({right:k.width()+l.width()+a.totalButtonsDistanceSeekBar+"px"}),b.showInfoBut&&t.css({bottom:b.borderWidth+"px"}),b.showPlaylistBut&&(r.css({display:"none"}),y.css({left:parseInt(y.css("left").substr(0,
y.css("left").lastIndexOf("px")),10)-r.width()-a.buttonsDistance+"px"})),e.width(a.new_width),e.height(a.new_height),e.css({top:"0px",left:"0px"}),f.css({left:0,bottom:"1px",background:b.controlsBgFullScreenColor}),g.css({bottom:b.borderWidth+"px"}),h.css({bottom:b.borderWidth+"px"}),w.css({bottom:b.borderWidth+30+"px"});a.haveYouTube&&d(".lbg_player",e).css({width:a.new_width+"px",height:a.new_height+"px"});a.haveVimeo&&d(".lbg_vimeo_player",e).css({width:a.new_width+"px",height:a.new_height+"px"});
la(a,e,n,a.new_width)}function ka(a,b,d){d.html('<div class="movieTitle">'+a.playlist_arr[a.origID].title+'</div><div class="movieDesc">'+a.playlist_arr[a.origID].desc+"</div>")}function oa(a){a=a.split(":");var b=0;3<=a.length?b+=3600*parseInt(a[0],10)+60*parseInt(a[1],10)+parseInt(a[2],10):2<=a.length?b+=60*parseInt(a[0],10)+parseInt(a[1],10):1<=a.length&&(b+=parseInt(a[0],10));return b}function ua(a,b,e,g,h,f,n,p,q,k,l,m,r,z,y,w,x){if("NO DATA!!!!"!=a&&-1==a.indexOf("404 Not Found")&&"#----##----#"!=
a&&-1==a.indexOf("simplexml_load_string()")){a=a.split("#----#");g.html(a[1]);b.cur_vast_link=a[2];ea();h.css("background","#000000");g=new Date;document.getElementById(b.html5_video_id).src=a[0]+"?time="+g.getTime();document.getElementById(b.html5_video_id).load();n.css("display","block");f.css("display","block");b.curTime=0;d("#"+b.html5_video_id).css({"z-index":4,width:"100%",height:"100%"});document.getElementById(b.html5_video_id).volume=e.initialVolume;document.getElementById(b.html5_video_id).play();
k.hasClass("pauseBut")||k.addClass("pauseBut");q.css({display:"block"});var t=parseInt(n.width(),10);b.skipad_timer=0;q.html(e.skip_add_text+(e.skip_ad_time>b.skipad_timer?e.skip_ad_time-b.skipad_timer:0)+"s");e.isSeekBarInitialized&&(f.slider("destroy"),e.isSeekBarInitialized=!1);b.selfHostedInterval=setInterval(function(){b.curTime=document.getElementById(b.html5_video_id).currentTime;b.totalTime=document.getElementById(b.html5_video_id).duration;b.skipad_timer=0<b.totalTime?b.curTime:0;q.html(e.skip_add_text+
(e.skip_ad_time>b.skipad_timer?parseInt(e.skip_ad_time-b.skipad_timer,10):0)+"s");!e.isSeekBarInitialized&&0<b.totalTime&&(f.slider({value:0,step:.5,orientation:"horizontal",range:"min",max:b.totalTime,create:function(a,b){e.isSeekBarInitialized=!0}}),d(".ui-slider-range",f).css({background:e.seekbarColor}));p.html(R(b.totalTime)+"/"+R(b.curTime+1));b.bufferedTime=document.getElementById(b.html5_video_id).buffered;b.is_buffer_complete||(b.bufferedTime=b.bufferedTime.length?parseFloat(document.getElementById(b.html5_video_id).buffered.end(0)):
document.getElementById(b.html5_video_id).buffered,0<b.bufferedTime&&n.progressbar({value:b.bufferedTime*t/b.totalTime}));!b.is_seeking&&e.isSeekBarInitialized&&f.slider("value",b.curTime+1)},1E3)}else X(1,b,e,h,l,g,n,f,p,k,m,r,z,y,w,x,q)}var r=navigator.userAgent.toLowerCase(),na=function(a){return document.getElementById(a).canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')};d.fn.universal_video_player=function(a){a=d.extend({},d.fn.universal_video_player.defaults,a);return this.each(function(){var b=
d(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=d(window).width(),responsiveHeight=d(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/
a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);b.css("display","block");var e=d("<div></div>").addClass("universal_video_playerBorder"),g=d("<div></div>").addClass("universal_video_player").addClass(a.skin),h=d('<div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <div class="slider-vertical"></div>      <div class="selectedCategDiv"><div class="innerSelectedCategDiv">READING CATEGORIES...</div></div>     <div class="searchDiv"><input class="search_term" type="text" value="search..." /></div>  <div class="top_title">Movie Title</div>  <div class="the_timer">00:00/00:00</div>  <div class="videoBuffer"></div> <div class="videoSeek"></div>                <div class="all_controls">             <div class="firstset_controls">                          <div class="rewindBut" title="Rewind"></div><div class="playBut" title="Play/Pause"></div> <div class="volumeAll"><div class="volumeSlider"></div><div class="volumeBut" title="Mute/Unmute"></div></div> <div class="facebookBut" title="Facebook"></div><div class="twitterBut" title="Twitter"></div><div class="infoBut"  title="Info"></div><div class="downloadBut" title="Download File"></div>          </div>           <div class="showHidePlaylistBut" title="Show/Hide Playlist"></div><div class="fullscreenBut" title="FullScreen"></div>  <div class="shuffleBut" title="Shuffle"></div><div class="prevBut" title="Previous"></div><div class="nextBut" title="Next"></div>              </div>             <div class="videoInfoBox"></div> <div class="skipAd"></div>');
b.wrap(g);b.after(h);var f=b.parent(".universal_video_player");f.wrap(e);var n=f.parent(".universal_video_playerBorder"),p=d(".selectedCategDiv",f),q=d(".innerSelectedCategDiv",f),k=d(".searchDiv",f),l=d(".search_term",f),m=d(".nextBut",f),t=d(".prevBut",f),z=d(".shuffleBut",f),y=d(".top_title",f),w=d(".the_timer",f),x=d(".all_controls",f),A=d(".videoBuffer",f),B=d(".videoSeek",f),D=d(".rewindBut",f),u=d(".playBut",f),M=d(".volumeAll",f),H=d(".volumeBut",f),Q=d(".volumeSlider",f),P=d(".facebookBut",
f),N=d(".twitterBut",f),I=d(".infoBut",f),J=d(".downloadBut",f),E=d(".showHidePlaylistBut",f),F=d(".fullscreenBut",f),G=d(".videoInfoBox",f),C=d(".skipAd",f);C.css({display:"none"});e=Math.floor(1E5*Math.random());g=d("<div></div>").addClass("lbg_player");b.append(g);var R="lbg_player"+e;d(".lbg_player",f).attr("id",R);g=d("<div></div>").addClass("lbg_vimeo_player");b.append(g);var K="lbg_vimeo_player"+e,ia=ea(),Y=a.defaultEffect,c={current_img_no:0,currentImg:0,current_imgInside:"",windowWidth:0,
carouselStep:0,thumbMarginTop:0,origThumbMarginTop:0,thumbsClicked:!1,haveYouTube:!1,haveVimeo:!1,haveSelfHosted:!1,html5_video_id:"html5_video_id_"+e,playerRatio:a.origWidth/a.origHeight,total_images:0,playlist_arr:"",category_arr:"",selectedCateg:"",categsAreListed:!1,numberOfCategories:0,universal_video_player_sliderVertical:"",search_val:"",is_very_first:!0,is_very_first_vimeo:!0,thumbsHolder_Thumb:"",thumbsHolder_Thumbs:"",containerOrigPosition:"",containerOrigZindex:"",youTubeInterval:"",selfHostedInterval:"",
vimeoInterval:"",bufferedTime:0,is_buffer_complete:!1,is_seeking:!1,totalTime:0,curTime:0,new_width:0,new_height:0,buttonsDistance:15,totalButtonsDistance:0,showPlaylistButOrigLeft:0,fullscreenButOrigLeft:0,origInfoWidth:0,origInfoHeight:0,origDownloadWidth:0,origDownloadHeight:0,buttonsDistanceSeekBar:7,totalButtonsDistanceSeekBar:0,minimalWidthSearch:445,minimalWidthDownload:370,minimalWidthInfo:340,showHidePlaylistMiliseconds:0,googleYouTubeCateg:"YouTube Videos",googleVimeoCateg:"Vimeo Videos",
googleSelfHostedCateg:"Self-Hosted Videos",ajaxReturnedImagesNo:0,totalImagesNo:0,videoIsFullScreen:!1,youtubeWasStarted:-1,origBodyTopMargin:0,origBodyRightMargin:0,origBodyBottomMargin:0,origBodyLeftMargin:0,origBodyOverflow:"",origHtmlOverflow:"",origID:0,previousOrigID:0,player:!1,isYouTubeReady:!1,vimeo_player:!1,vimeo_iframe:!1,is_vast:!1,skipad_timer:0};c.origInfoWidth=I.width();c.origInfoHeight=I.height();c.origDownloadWidth=J.width();c.origDownloadHeight=J.height();c.containerOrigPosition=
f.css("position");c.containerOrigZindex=f.css("z-index");c.origBodyTopMargin=d("body").css("margin-top");c.origBodyRightMargin=d("body").css("margin-right");c.origBodyBottomMargin=d("body").css("margin-bottom");c.origBodyLeftMargin=d("body").css("margin-left");c.origBodyOverflow=d("body").css("overflow");c.origHtmlOverflow=d("html").css("overflow");var L=d(".thumbsHolderWrapper",f),W=d(".thumbsHolderVisibleWrapper",f),T=d(".thumbsHolder",f);c.universal_video_player_sliderVertical=d(".slider-vertical",
f);L.css({background:a.playlistBgColor});a.showTopTitle?y.css({color:a.topTitleColor,top:-1*a.borderWidth+(a.borderWidth-y.height())/2+"px"}):y.css({display:"none"});a.showTimer?w.css({color:a.timerColor,top:-1*a.borderWidth+(a.borderWidth-w.height())/2+"px"}):w.css({display:"none"});n.width(a.width);n.height(a.height);n.css("background",a.borderColor);c.new_width=parseInt(a.width-a.playlistWidth/(a.origWidth/a.width)-3*a.borderWidth,10);f.width(c.new_width);f.height(a.height-2*a.borderWidth);f.css({left:a.borderWidth+
"px",top:a.borderWidth+"px"});d(".lbg_player",f).width(c.new_width);d(".lbg_player",f).height(f.height());d(".lbg_vimeo_player",f).width(c.new_width);d(".lbg_vimeo_player",f).height(f.height());W.width(a.playlistWidth/(a.origWidth/a.width));W.height(f.height());L.width(a.playlistWidth/(a.origWidth/a.width));L.height(f.height());L.css({top:0,right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});T.width(a.playlistWidth/(a.origWidth/a.width));T.css("top","0px");p.css({width:a.playlistWidth/
(a.origWidth/a.width)+"px","background-color":a.selectedCategBg,"background-position":"2px 50%",top:"-20px",right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});q.css({color:a.selectedCategOffColor,"background-position":a.playlistWidth/(a.origWidth/a.width)-9+"px 50%"});var v=b.find("ul:first").children();c.playlist_arr=[];c.category_arr=[];var V=[];v.each(function(){c.currentImg=d(this);c.currentImg.is("li")||(c.currentImg=c.currentImg.find("li:first"));if(c.currentImg.is("li")){c.currentImg.css("display",
"none");c.total_images++;c.playlist_arr[c.total_images-1]=[];c.playlist_arr[c.total_images-1].title="";c.playlist_arr[c.total_images-1].desc="";c.playlist_arr[c.total_images-1]["bottom-thumb"]="";c.playlist_arr[c.total_images-1].category="";c.playlist_arr[c.total_images-1].youtube="";c.playlist_arr[c.total_images-1].vimeo="";c.playlist_arr[c.total_images-1].selfhostedMP4="";c.playlist_arr[c.total_images-1].selfhostedWEBM="";c.playlist_arr[c.total_images-1].startpoint="";c.playlist_arr[c.total_images-
1].endpoint="";void 0!=d(v[c.total_images-1]).attr("data-title")&&""!=d(v[c.total_images-1]).attr("data-title")&&(c.playlist_arr[c.total_images-1].title=d(v[c.total_images-1]).attr("data-title"));void 0!=d(v[c.total_images-1]).attr("data-desc")&&""!=d(v[c.total_images-1]).attr("data-desc")&&(c.playlist_arr[c.total_images-1].desc=d(v[c.total_images-1]).attr("data-desc"));void 0!=d(v[c.total_images-1]).attr("data-bottom-thumb")&&""!=d(v[c.total_images-1]).attr("data-bottom-thumb")&&(c.playlist_arr[c.total_images-
1]["bottom-thumb"]=d(v[c.total_images-1]).attr("data-bottom-thumb"));void 0!=d(v[c.total_images-1]).attr("data-youtube")&&""!=d(v[c.total_images-1]).attr("data-youtube")&&(c.playlist_arr[c.total_images-1].youtube=d(v[c.total_images-1]).attr("data-youtube"));void 0!=d(v[c.total_images-1]).attr("data-vimeo")&&""!=d(v[c.total_images-1]).attr("data-vimeo")&&(c.playlist_arr[c.total_images-1].vimeo=d(v[c.total_images-1]).attr("data-vimeo"));void 0!=d(v[c.total_images-1]).attr("data-selfhostedMP4")&&""!=
d(v[c.total_images-1]).attr("data-selfhostedMP4")&&(c.playlist_arr[c.total_images-1].selfhostedMP4=d(v[c.total_images-1]).attr("data-selfhostedMP4"));void 0!=d(v[c.total_images-1]).attr("data-selfhostedWEBM")&&""!=d(v[c.total_images-1]).attr("data-selfhostedWEBM")&&(c.playlist_arr[c.total_images-1].selfhostedWEBM=d(v[c.total_images-1]).attr("data-selfhostedWEBM"));void 0!=d(v[c.total_images-1]).attr("data-startpoint")&&""!=d(v[c.total_images-1]).attr("data-startpoint")&&(c.playlist_arr[c.total_images-
1].startpoint=d(v[c.total_images-1]).attr("data-startpoint"));void 0!=d(v[c.total_images-1]).attr("data-endpoint")&&""!=d(v[c.total_images-1]).attr("data-endpoint")&&(c.playlist_arr[c.total_images-1].endpoint=d(v[c.total_images-1]).attr("data-endpoint"));void 0!=d(v[c.total_images-1]).attr("data-vast")&&""!=d(v[c.total_images-1]).attr("data-vast")&&(c.playlist_arr[c.total_images-1].vast=d(v[c.total_images-1]).attr("data-vast"));if(void 0!=d(v[c.total_images-1]).attr("data-category")&&""!=d(v[c.total_images-
1]).attr("data-category")){c.playlist_arr[c.total_images-1].category=d(v[c.total_images-1]).attr("data-category")+";";V=d(v[c.total_images-1]).attr("data-category").split(";");for(var a=0;a<V.length;a++)-1===c.category_arr.indexOf(V[a])&&c.category_arr.push(V[a])}void 0!=d(v[c.total_images-1]).attr("data-youtube")&&""!=d(v[c.total_images-1]).attr("data-youtube")&&(c.haveYouTube=!0);void 0!=d(v[c.total_images-1]).attr("data-vimeo")&&""!=d(v[c.total_images-1]).attr("data-vimeo")&&(c.haveVimeo=!0);void 0!=
d(v[c.total_images-1]).attr("data-selfhostedMP4")&&""!=d(v[c.total_images-1]).attr("data-selfhostedMP4")&&(c.haveSelfHosted=!0)}});c.numberOfCategories=c.category_arr.length;c.category_arr.sort();c.selectedCateg=a.firstCateg;""==a.firstCateg&&-1===c.category_arr.indexOf(a.firstCateg)&&(c.selectedCateg=c.category_arr[0]);q.html(c.selectedCateg);var aa=d(".thumbsHolder_ThumbOFF .padding",f);var ba=d(".thumbsHolder_ThumbOFF .title",f);var ca=d(".thumbsHolder_ThumbOFF .reg",f);for(c.totalImagesNo=0;c.totalImagesNo<
c.playlist_arr.length;c.totalImagesNo++)""!=c.playlist_arr[c.totalImagesNo].youtube&&a.getYouTubeData?d.get(a.pathToAjaxFiles+"get_gdata.php",{cur_i:c.totalImagesNo,youtubeID:c.playlist_arr[c.totalImagesNo].youtube},function(b){c.ajaxReturnedImagesNo++;b=b.split("#----#");the_i=parseInt(b[0],10);if(void 0==c.playlist_arr[the_i]["bottom-thumb"]||""==c.playlist_arr[the_i]["bottom-thumb"])c.playlist_arr[the_i]["bottom-thumb"]=b[1];if(void 0==c.playlist_arr[the_i].title||""==c.playlist_arr[the_i].title)c.playlist_arr[the_i].title=
b[2];if(void 0==c.playlist_arr[the_i].desc||""==c.playlist_arr[the_i].desc)c.playlist_arr[the_i].desc=b[3];the_i==a.firstVideo&&ka(c,a,G);c.ajaxReturnedImagesNo==c.totalImagesNo&&ha(c,a,f,T,L,W,p,k,aa,ba,ca,y,A,B,w,u,G,x,E,F,K,R,D,M,P,N,I,J,ia,m,C,H)}):c.ajaxReturnedImagesNo++;a.getYouTubeData?c.haveYouTube||ha(c,a,f,T,L,W,p,k,aa,ba,ca,y,A,B,w,u,G,x,E,F,K,R,D,M,P,N,I,J,ia,m,C,H):ha(c,a,f,T,L,W,p,k,aa,ba,ca,y,A,B,w,u,G,x,E,F,K,R,D,M,P,N,I,J,ia,m,C,H);e=d("<div></div>").addClass("largePlayButton");
f.append(e);d(".largePlayButton",f).click(function(){c.is_vast?window.open(c.cur_vast_link,a.ad_link_target):u.click()});O(c,c.origID)&&d(".largePlayButton",f).css({display:"none"});e=d("<div></div>").addClass("fullscreenVimeoButton");f.append(e);d(".fullscreenVimeoButton",f).mouseover(function(){d(this).css({background:"url("+a.absUrl+"skins/"+a.skin+"/fullscreenvimeo.png) no-repeat left bottom"})});d(".fullscreenVimeoButton",f).mouseout(function(){d(this).css({background:"none"})});e=d('<a href="'+
a.logoLink+'" target="'+a.logoTarget+'"><img src="'+a.logoImagePath+'"></a>').addClass("yourLogo");f.append(e);a.showLogo||d(".yourLogo",f).css({display:"none"});a.showRewindBut&&D.click(function(){if(!c.is_vast){var a;U(c,c.origID)&&(document.getElementById(c.html5_video_id).currentTime=0,document.getElementById(c.html5_video_id).play());O(c,c.origID)&&0!=c.isYouTubeReady&&(a=-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?
c.youtubeWasStarted==YT.PlayerState.PLAYING?!0:!1:!0)&&(c.player.seekTo(0),c.player.playVideo())}});a.showPlayBut&&(u.mouseover(function(){c.is_vast||u.css({"background-color":a.playButColorOn})}),u.mouseout(function(){c.is_vast||u.css({"background-color":a.playButColorOff})}),u.click(function(){var a;U(c,c.origID)&&(u.hasClass("pauseBut")?(document.getElementById(c.html5_video_id).pause(),u.removeClass("pauseBut")):(document.getElementById(c.html5_video_id).play(),u.addClass("pauseBut")));O(c,c.origID)&&
0!=c.isYouTubeReady&&(a=-1!=r.indexOf("ipad")||-1!=r.indexOf("iphone")||-1!=r.indexOf("ipod")||-1!=r.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?c.youtubeWasStarted==YT.PlayerState.PLAYING?!0:!1:!0)&&(u.hasClass("pauseBut")?(c.player.pauseVideo(),u.removeClass("pauseBut")):(c.player.playVideo(),u.addClass("pauseBut")))}));a.showVolumeBut&&(Q.slider({value:a.initialVolume,orientation:"vertical",range:"max",max:1,step:.05,animate:!0,slide:function(b,e){d("iframe",f).css({"pointer-events":"none"});
a.initialVolume=e.value;O(c,c.origID)&&0!=c.isYouTubeReady&&(c.player.unMute(),H.removeClass("volumeButtonMute"),c.player.setVolume(100*a.initialVolume));U(c,c.origID)&&(document.getElementById(c.html5_video_id).muted=!1,document.getElementById(c.html5_video_id).volume=a.initialVolume,H.removeClass("volumeButtonMute"))},stop:function(a,b){d("iframe",f).css({"pointer-events":"auto"})}}),Q.css({background:a.volumeOnColor}),Q.css({"border-color":a.volumeOffColor}),d(".ui-slider-range",Q).css({background:a.volumeOffColor}),
M.mouseover(function(){Q.css({display:"block"})}),M.mouseout(function(){Q.css({display:"none"})}),H.click(function(){c.haveYouTube&&0!=c.isYouTubeReady&&(c.player.isMuted()?(H.removeClass("volumeButtonMute"),c.player.unMute(),c.player.setVolume(100*a.initialVolume)):(H.addClass("volumeButtonMute"),c.player.setVolume(0),c.player.mute()));c.haveSelfHosted&&(1==document.getElementById(c.html5_video_id).muted?(document.getElementById(c.html5_video_id).muted=!1,document.getElementById(c.html5_video_id).volume=
a.initialVolume,H.removeClass("volumeButtonMute")):(document.getElementById(c.html5_video_id).muted=!0,document.getElementById(c.html5_video_id).volume=0,H.addClass("volumeButtonMute")))}));a.showFacebookBut&&(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,version:"v2.8",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,
"script","facebook-jssdk"),P.click(function(){c.is_vast||FB.ui({method:"feed",name:a.facebookShareTitle,caption:c.playlist_arr[c.origID].title,description:a.facebookShareDescription,link:document.URL},function(a){})}));a.showTwitterBut&&N.click(function(){c.is_vast||window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+c.playlist_arr[c.origID].title,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});a.showInfoBut&&(I.click(function(){c.is_vast||
G.slideToggle(500,"easeOutCirc")}),ka(c,a,G));a.showDownloadBut&&J.click(function(){c.is_vast||O(c,c.origID)||S(c,c.origID)||window.open(a.pathToDownloadFile+"download.php?the_file="+c.playlist_arr[c.origID].selfhostedMP4)});E.click(function(){c.is_vast||(a.showPlaylistOnInit||L.css("visibility","visible"),"none"!=L.css("display")?(a.playlistVisible=!1,c.new_width=parseInt(a.width-2*a.borderWidth,10),f.width(c.new_width),L.css({display:"none"}),a.showCategs&&p.css({display:"none"}),a.showSearch&&
k.css({display:"none"}),a.isPlaylistSliderInitialized&&c.universal_video_player_sliderVertical.css({visibility:"hidden"}),a.showNextPrevBut&&(m.css({right:0}),t.css({right:m.width()+c.buttonsDistanceSeekBar+"px"})),a.showShuffleBut&&z.css({right:m.width()+t.width()+c.totalButtonsDistanceSeekBar+"px"})):(c.showHidePlaylistMiliseconds=300,a.playlistVisible=!0,c.new_width=parseInt(a.width-a.playlistWidth/(a.origWidth/a.width)-3*a.borderWidth,10),f.width(c.new_width),L.css({display:"block"}),a.showCategs&&
p.css({display:"block"}),!a.showSearch||a.width<=c.minimalWidthSearch||k.css({display:"block"}),a.isPlaylistSliderInitialized&&c.universal_video_player_sliderVertical.css({visibility:"visible"}),a.showNextPrevBut&&(m.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"}),t.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-m.width()-c.buttonsDistanceSeekBar)+"px"})),a.showShuffleBut&&z.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-m.width()-
t.width()-c.totalButtonsDistanceSeekBar)+"px"})),c.haveYouTube&&d(".lbg_player",f).animate({width:c.new_width+"px"},c.showHidePlaylistMiliseconds,"easeOutQuad",function(){}),c.haveVimeo&&d(".lbg_vimeo_player",f).animate({width:c.new_width+"px"},c.showHidePlaylistMiliseconds,"easeOutQuad",function(){}),la(c,f,L,c.new_width))});a.showFullscreenBut&&(F.click(function(){screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")?screenfull.toggle():qa(c,a,f,A,B,x,L,p,k,m,t,z,G,E,F,C)}),c.totalButtonsDistance+=
c.buttonsDistance);d(".fullscreenVimeoButton",f).click(function(){c.is_vast||(screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")?screenfull.toggle():qa(c,a,f,A,B,x,L,p,k,m,t,z,G,E,F,C))});O(c,c.origID)&&d(".fullscreenVimeoButton",f).css({display:"none"});screenfull.enabled&&-1==navigator.userAgent.indexOf("Android")&&document.addEventListener(screenfull.raw.fullscreenchange,function(){delayTime=50;11<=ia&&(delayTime=200);setTimeout(function(){qa(c,a,f,A,B,x,L,p,k,m,t,z,G,E,F,C)},delayTime)});
c.totalButtonsDistanceSeekBar=0;a.showNextPrevBut?(m.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px",bottom:"0px"}),m.click(function(){c.is_vast||c.categsAreListed||(c.curTime=0,X(1,c,a,f,T,y,A,B,w,u,G,x,E,F,K,m,C))}),t.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-m.width()-c.buttonsDistanceSeekBar)+"px",bottom:"0px"}),t.click(function(){c.is_vast||c.categsAreListed||X(-1,c,a,f,T,y,A,B,w,u,G,x,E,F,K,m,C)}),c.totalButtonsDistanceSeekBar=3*c.buttonsDistanceSeekBar):
(m.css({display:"none",width:0,height:0,padding:0,margin:0}),t.css({display:"none",width:0,height:0,padding:0,margin:0}));a.showShuffleBut?(z.css({right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width)-m.width()-t.width()-c.totalButtonsDistanceSeekBar)+"px",bottom:"0px"}),a.shuffle&&z.addClass("VideoShuffleON"),z.click(function(){c.is_vast||(a.shuffle?(z.removeClass("VideoShuffleON"),a.shuffle=!1):(z.addClass("VideoShuffleON"),a.shuffle=!0))})):z.css({display:"none",width:0,height:0,padding:0,
margin:0});C.click(function(){c.skipad_timer>=a.skip_ad_time&&X(1,c,a,f,T,y,A,B,w,u,G,x,E,F,K,m,C)});T.swipe({swipeStatus:function(b,f,e,g,h,k){"up"!=e&&"down"!=e||0==g||(currentScrollVal=c.universal_video_player_sliderVertical.slider("value"),currentScrollVal="up"==e?currentScrollVal-1.5:currentScrollVal+1.5,c.universal_video_player_sliderVertical.slider("value",currentScrollVal),d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),da(currentScrollVal,
T,a,c))},threshold:100,maxTimeThreshold:500,fingers:"all"});k.css({width:a.playlistWidth/(a.origWidth/a.width)+"px","background-color":a.searchAreaBg,top:3+(a.height-2*a.borderWidth)+"px",right:-1*(a.borderWidth+a.playlistWidth/(a.origWidth/a.width))+"px"});l.val(a.searchInputText);l.css({width:parseInt(a.playlistWidth/(a.origWidth/a.width),10)-100+"px","background-color":a.searchInputBg,"border-color":a.searchInputBorderColor,color:a.searchInputTextColor});void 0!=c.currentImg.vimeo&&""!=c.currentImg.vimeo&&
fa(c,a,f,A,B,x,"none");a.showSearch?(l.on("click",function(){d(this).val("")}),l.on("input",function(){c.search_val=l.val().toLowerCase();ha(c,a,f,T,L,W,p,k,aa,ba,ca,y,A,B,w,u,G,x,E,F,K,R,D,M,P,N,I,J,ia,m,C,H)})):l.css({display:"none"});a.showCategs?(p.click(function(){c.is_vast||(c.search_val="",l.val(a.searchInputText),Ba(c,a,f,T,L,W,p,q,k,aa,ba,ca,y,A,B,w,u,G,x,E,F,K,R,D,M,P,N,I,J,m,C,H))}),p.mouseover(function(){q.css({color:a.selectedCategOnColor})}),p.mouseout(function(){q.css({color:a.selectedCategOffColor})})):
p.css({display:"none"});a.origWidth!=a.width&&ma(c,a,Y,b,h,f,n,T,W,L,aa,ba,ca,p,q,k,l,D,u,M,P,N,I,J,E,F,m,t,z,A,B,x,K);a.showPlaylistOnInit?c.showHidePlaylistMiliseconds=300:(c.showHidePlaylistMiliseconds=0,L.css("visibility","hidden"),setTimeout(function(){E.click()},100));0===a.initialVolume&&setTimeout(function(){c.haveYouTube?0!=c.isYouTubeReady?H.click():setTimeout(function(){H.click()},2E3):H.click()},1500);var Z=!1,ja=!0;d(window).resize(function(){var e=ea();ja=!0;-1!=e&&9==e&&0==c.windowWidth&&
(ja=!1);c.windowWidth==d(window).width()?(ja=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,ja=!0)):c.windowWidth=d(window).width();a.responsive&&ja&&(!1!==Z&&clearTimeout(Z),Z=setTimeout(function(){ma(c,a,Y,b,h,f,n,T,W,L,aa,ba,ca,p,q,k,l,D,u,M,P,N,I,J,E,F,m,t,z,A,B,x,K)},300))})})};d.fn.myReverse=[].reverse;d.fn.universal_video_player.defaults={skin:"whiteControllers",width:980,height:399,width100Proc:!1,height100Proc:!1,
shuffle:!1,firstVideo:0,initialVolume:1,loop:!0,showCategs:!0,showSearch:!0,showTopTitle:!0,showTimer:!0,showRewindBut:!0,showPlayBut:!0,showVolumeBut:!0,showFacebookBut:!0,facebookAppID:"1620027148224169",facebookShareTitle:"Universal Video Player",facebookShareDescription:"A top-notch responsive HTML5 Video Player compatible with all major browsers and mobile devices.",showTwitterBut:!0,showInfoBut:!0,showDownloadBut:!0,showPlaylistBut:!0,showFullscreenBut:!0,showShuffleBut:!0,showNextPrevBut:!0,
borderWidth:20,borderColor:"#4a4a4a",playlistWidth:282,absUrl:"",pathToDownloadFile:"",suggestedQuality:"default",controlsBgFullScreenColor:"#000000",playlistVisible:!0,playlistScrollerBgColorOFF:"#CCCCCC",playlistScrollerBgColorON:"#FFFFFF",responsive:!0,responsiveRelativeToBrowser:!1,numberOfThumbsPerScreen:0,origNumberOfThumbsPerScreen:0,logoImagePath:"skins/logo_watermark.png",logoLink:"http://codecanyon.net/user/LambertGroup?ref=LambertGroup",logoTarget:"_blank",showLogo:!0,autoPlayFirstVideo:!0,
autoPlayOnMobile:!1,playlistRecordShowImg:!0,playlistRecordShowTitle:!0,playlistRecordShowDesc:!0,playlistRecordHeight:89,playlistRecordPadding:10,playlistTitleFontSize:15,playlistTitleLineHeight:19,playlistDescFontSize:12,playlistDescLineHeight:15,playlistRecordBgOffColor:"#eeeeee",playlistRecordTitleOffColor:"#333333",playlistRecordDescOffColor:"#333333",playlistRecordBgOffImgOpacity:100,playlistRecordBgOnColor:"#de1a21",playlistRecordTitleOnColor:"#FFFFFF",playlistRecordDescOnColor:"#FFFFFF",playlistRecordBgOnImgOpacity:100,
playlistBgColor:"#4a4a4a",playlistRecordTitleLimit:22,playlistRecordDescLimit:84,getYouTubeData:!1,pathToAjaxFiles:"",showPlaylistOnInit:!0,categoryRecordBgOffColor:"#000000",categoryRecordBgOnColor:"#252525",categoryRecordBottomBorderOffColor:"#333333",categoryRecordBottomBorderOnColor:"#333333",categoryRecordTextOffColor:"#4c4c4c",categoryRecordTextOnColor:"#de1a21",firstCateg:"",selectedCategBg:"transparent",selectedCategOffColor:"#FFFFFF",selectedCategOnColor:"#de1a28",searchAreaBg:"transparent",
searchInputText:"search...",searchInputBg:"#cccccc",searchInputBorderColor:"#4a4a4a",searchInputTextColor:"#333333",topTitleColor:"#FFFFFF",timerColor:"#FFFFFF",bufferEmptyColor:"#929292",bufferFullColor:"#333333",seekbarColor:"#ffffff",volumeOffColor:"#454545",volumeOnColor:"#ffffff",isBufferInitialized:!1,isSeekBarInitialized:!1,playButColorOff:"#de1a21",playButColorOn:"#de1a21",youtubeJsUrl:"https://www.youtube.com/iframe_api",vimeoJsUrl:"http://a.vimeocdn.com/js/froogaloop2.min.js",googleTrakingOn:!1,
googleTrakingCode:"",origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origThumbImgW:69,origThumbImgH:69,origthumbLeftPadding:0,origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,origthumbTitleFont:0,origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0,isPlaylistSliderInitialized:!1,skip_add_text:"You can skip this video in: ",
skip_ad_time:5,ad_link_target:"_blank"}})(jQuery);
