/*
 * Universal Video Background v1.8.5
 *
 * Copyright 2014-2018, LambertGroup
 *
*/


(function(c){function D(a,b,c){c.css({background:a.thumbsBgOffColor,"border-color":a.thumbsBorderColorOFF});c.find("img:first").css({opacity:a.thumbsBgOffImgOpacity/100,filter:"alpha(opacity="+a.thumbsBgOffImgOpacity+")"})}function G(a,b,c){c.css({background:a.thumbsBgOnColor,"border-color":a.thumbsBorderColorON});c.find("img:first").css({opacity:a.thumbsBgOnImgOpacity/100,filter:"alpha(opacity="+a.thumbsBgOnImgOpacity+")"})}function E(a,b,e,f,g,r,h,n,l,v,k,t){var u=!0;if(!e.loop&&b.current_img_no+
a>=f||!e.loop&&0>b.current_img_no+a)u=!1;u&&(D(e,b,c(g[b.current_img_no])),K(b,e,r,v),e.randomizeVideos&&!b.bottomNavClicked?(a=Math.floor(Math.random()*f),b.current_img_no=b.current_img_no===a?Math.floor(Math.random()*f):a):b.current_img_no=b.current_img_no+a>=f?0:0>b.current_img_no+a?f-1:b.current_img_no+a,G(e,b,c(g[b.current_img_no])),currentCarouselLeft=n.css("left").substr(0,n.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===f-1?A(0,n,k,t,e,f,h,b):A(1001,n,k,t,e,f,h,b),
b.currentImg=c(l[b.current_img_no]),b.bottomNavClicked=!1,void 0!=b.currentImg.attr("data-youtube")&&""!=b.currentImg.attr("data-youtube")||void 0!=b.currentImg.attr("data-vimeo")&&""!=b.currentImg.attr("data-vimeo")||void 0!=b.currentImg.attr("data-selfhostedMP4")&&""!=b.currentImg.attr("data-selfhostedMP4"))&&(H(b,e,r,v,l),e.width100Proc&&e.height100Proc&&e.setAsBg&&I(b,e,l,r))}function A(a,b,c,f,g,r,h,n){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?
(n.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*n.carouselStep},600,"easeOutCubic",function(){B(n,b,c,f,g,r,h);n.isCarouselScrolling=!1})):currentCarouselLeft!=-1*Math.floor(n.current_img_no/g.numberOfThumbsPerScreen)*n.carouselStep&&(n.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(n.current_img_no/g.numberOfThumbsPerScreen)*n.carouselStep},600,"easeOutCubic",function(){B(n,b,c,f,g,r,h);n.isCarouselScrolling=!1}))}function B(a,
b,c,f,g,r,h){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?c.hasClass("carouselLeftNavDisabled")&&c.removeClass("carouselLeftNavDisabled"):c.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(2*a.thumbBorderWidth+h.width()+a.thumbMarginLeft)*r?f.hasClass("carouselRightNavDisabled")&&f.removeClass("carouselRightNavDisabled"):f.addClass("carouselRightNavDisabled")}function L(a,b,e,f,g,r,h,n,l,v,k){k.height(parseInt(b.origthumbsHolderWrapperH/
(b.origWidth/b.width),10));parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)<b.thumbsWrapperMinHeight&&k.height(b.thumbsWrapperMinHeight);k.css({top:b.height-2*parseInt(b.borderWidth/(b.origWidth/b.width),10)-k.height()-parseInt(b.thumbsWrapperMarginTop/(b.origWidth/b.width),10)+"px",width:b.width-2*parseInt(b.borderWidth/(b.origWidth/b.width),10)+"px","padding-top":parseInt(b.thumbsWrapperTopPadding/(b.origWidth/b.width),10),"padding-bottom":parseInt(b.thumbsWrapperBottomPadding/(b.origWidth/
b.width),10),"border-left":parseInt(b.borderWidth/(b.origWidth/b.width),10)+"px solid "+b.borderColor,"border-right":parseInt(b.borderWidth/(b.origWidth/b.width),10)+"px solid "+b.borderColor,left:-1*parseInt(b.borderWidth/(b.origWidth/b.width)+.5,10)+"px"});bgTopCorrection=1;h.css("background-position","0px "+((k.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px");n.css("background-position","0px "+((k.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px");v.css("width",b.width-
2*parseInt(b.borderWidth/(b.origWidth/b.width),10)-h.width()-n.width());b.origWidthThumbsHolderVisibleWrapper=b.origWidth-h.width()-n.width();g.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/v.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/v.width()),10)+"px"});c(".thumbsHolder_ThumbOFF",f).find("img:first").css({width:g.width()+"px",height:g.height()+"px"});parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)<b.thumbsWrapperMinHeight?
v.css({top:parseInt((k.height()-g.height())/2,10)+"px"}):v.css({top:"auto"});a.thumbMarginLeft=Math.floor((k.width()-h.width()-n.width()-(2*a.thumbBorderWidth+l.width())*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1));thumb_i=-1;r.children().each(function(){thumb_i++;theThumb=c(this);0>=thumb_i?theThumb.css("margin-left",Math.floor((k.width()-h.width()-n.width()-(a.thumbMarginLeft+(2*a.thumbBorderWidth+theThumb.width()))*(b.numberOfThumbsPerScreen-1)-(2*a.thumbBorderWidth+theThumb.width()))/
2)+"px"):theThumb.css("margin-left",a.thumbMarginLeft+"px")});a.carouselStep=(2*a.thumbBorderWidth+l.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen;if(b.numberOfThumbsPerScreen>=e)switch(b.bottomNavPos){case "left":v.css("left",b.bottomNavLateralMargin+a.thumbMarginLeft+"px");break;case "right":v.css("left",b.width-(2*a.thumbBorderWidth+g.width()+a.thumbMarginLeft)*e-b.bottomNavLateralMargin+"px");break;default:v.css("left",parseInt((k.width()-(2*a.thumbBorderWidth+l.width()+a.thumbMarginLeft)*
e)/2,10)+"px")}}function I(a,b,e,f){b=b.videoProportionWidth;void 0!=c(e[a.current_img_no]).attr("data-videoProportionWidth")&&""!=c(e[a.current_img_no]).attr("data-videoProportionWidth")&&(b=c(e[a.current_img_no]).attr("data-videoProportionWidth"));e=parseInt(1280/b*9,10);windowW=c(window).width()+1;windowH=c(window).height();var g=1/(1280/windowW);e/windowH<1280/windowW&&(g=1/(e/windowH));16!=b&&(g+=.11);a.haveYouTube&&c(".lbg_player",f).css({width:1280*g+"px",height:e*g+"px",left:parseInt((windowW-
1280*g)/2,10)+"px",top:parseInt((windowH-e*g)/2,10)+"px"});a.haveVimeo&&c(".lbg_vimeo_player",f).css({width:1280*g+"px",height:e*g+"px",left:parseInt((windowW-1280*g)/2,10)+"px",top:parseInt((windowH-e*g)/2,10)+"px"});a.haveSelfHosted&&c("#"+a.html5_video_id).css({width:1280*g+"px",height:e*g+"px",left:parseInt((windowW-1280*g)/2,10)+"px",top:parseInt((windowH-e*g)/2,10)+"px"})}function F(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent,c=/MSIE ([0-9]{1,}[.0-9]{0,})/;
null!=c.exec(b)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(b=navigator.userAgent,c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=c.exec(b)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function M(a,b,c){var e=b.attr("data-selfhostedWEBM"),g=navigator.userAgent.toLowerCase();if(-1!=g.indexOf("chrome")||-1!=g.indexOf("msie")||-1!=g.indexOf("safari")||-1!=g.indexOf("android"))e=b.attr("data-selfhostedMP4");if(-1!=g.indexOf("ipad")||-1!=g.indexOf("iphone")||-1!=g.indexOf("ipod")||
-1!=g.indexOf("webos"))e=b.attr("data-selfhostedMP4");-1!=g.indexOf("android")&&(e=b.attr("data-selfhostedMP4"));-1!=a&&(e=b.attr("data-selfhostedMP4"));-1!=g.indexOf("opera")&&(e=b.attr("data-selfhostedWEBM"),""!=z(c)&&(e=b.attr("data-selfhostedMP4")));-1!=g.indexOf("opr/")&&(e=b.attr("data-selfhostedWEBM"),""!=z(c)&&(e=b.attr("data-selfhostedMP4")));if(-1!=g.indexOf("firefox")||-1!=g.indexOf("mozzila"))e=b.attr("data-selfhostedWEBM"),""!=z(c)&&(e=b.attr("data-selfhostedMP4"));return e}function K(a,
b,e,f){void 0!=a.currentImg.attr("data-youtube")&&""!=a.currentImg.attr("data-youtube")&&a.haveYouTube&&(a.player.stopVideo(),b.initialVolume=a.player.getVolume()/100,a.player.isMuted()&&(b.initialVolume=0),c(".lbg_player",e).css({"z-index":-1}));void 0!=a.currentImg.attr("data-vimeo")&&""!=a.currentImg.attr("data-vimeo")&&a.haveVimeo&&(a.vimeo_player.pause(),c(".lbg_vimeo_player",e).css({"z-index":-1}),c(".lbg_vimeo_player",e).css({"z-index":-1}),a.vimeo_player.getVolume().then(function(c){b.initialVolume=
c;a.haveYouTube&&a.player.setVolume(100*b.initialVolume);a.haveSelfHosted&&(document.getElementById(a.html5_video_id).volume=b.initialVolume)})["catch"](function(a){}));void 0!=a.currentImg.attr("data-selfhostedMP4")&&""!=a.currentImg.attr("data-selfhostedMP4")&&a.haveSelfHosted&&(document.getElementById(a.html5_video_id).pause(),b.initialVolume=document.getElementById(a.html5_video_id).volume,document.getElementById(a.html5_video_id).muted&&(b.initialVolume=0),c("#"+a.html5_video_id).css({"z-index":-1,
width:0,height:0}))}function H(a,b,e,f,g){b.autoPlayFirstVideo=!0;void 0!=a.currentImg.attr("data-youtube")&&""!=a.currentImg.attr("data-youtube")&&a.haveYouTube&&(e.css("background","#000000"),-1!=l.indexOf("ipad")||-1!=l.indexOf("iphone")||-1!=l.indexOf("ipod")||-1!=l.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?a.player.cueVideoById(a.currentImg.attr("data-youtube")):a.player.loadVideoById(a.currentImg.attr("data-youtube"),0,b.suggestedQuality),a.player.setVolume(100*b.initialVolume),
0<b.initialVolume&&a.player.unMute(),c(".lbg_player",e).css({"z-index":0}));void 0!=a.currentImg.attr("data-vimeo")&&""!=a.currentImg.attr("data-vimeo")&&a.haveVimeo&&(e.css("background","#000000"),a.vimeo_player.unload(),a.vimeo_player.loadVideo(a.currentImg.attr("data-vimeo")).then(function(c){a.vimeo_player.setVolume(b.initialVolume);b.loop&&-1==l.indexOf("ipad")&&-1==l.indexOf("iphone")&&-1==l.indexOf("ipod")&&-1==l.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&a.vimeo_player.play()})["catch"](function(a){switch(a.name){case "TypeError":alert("the id was not a number");
break;case "PasswordError":alert("password first");break;case "PrivacyError":alert("the video is password-protected or private");break;default:alert("some other error occurred")}}),c(".lbg_vimeo_player",e).css({"z-index":4}));void 0!=a.currentImg.attr("data-selfhostedMP4")&&""!=a.currentImg.attr("data-selfhostedMP4")&&a.haveSelfHosted&&(f=F(),e.css("background","#000000"),e=new Date,document.getElementById(a.html5_video_id).src=M(f,a.currentImg,a.html5_video_id)+"?time="+e.getTime(),document.getElementById(a.html5_video_id).load(),
c("#"+a.html5_video_id).css({"z-index":0,width:"100%",height:"100%"}),document.getElementById(a.html5_video_id).volume=b.initialVolume,document.getElementById(a.html5_video_id).play())}function P(a,b){a.showTooltip&&c(".lbg_grid_tooltip").tooltip({content:function(){return c(b[c(this).attr("rel")]).attr("data-title")},position:{my:"center bottom-20",at:"center top",using:function(a,b){c(this).css(a);c("<div>").addClass("lbg_grid_arrow").addClass(b.vertical).addClass(b.horizontal).appendTo(this)}}})}
var l=navigator.userAgent.toLowerCase(),z=function(a){return document.getElementById(a).canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')};c.fn.universal_video_background=function(a){a=c.extend({},c.fn.universal_video_background.defaults,a);return this.each(function(){var b=F(),e=c(this);responsiveWidth=e.parent().width();responsiveHeight=e.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());a.origWidth=a.width;a.width100Proc&&
(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);a.width100Proc&&a.height100Proc&&(a.borderWidth=0);e.css("display","block");var f=c("<div></div>").addClass("universal_video_backgroundBorder"),
g=c("<div></div>").addClass("universal_video_background").addClass(a.skin),r=c('<div class="bannerControls">   <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>       </div>  ');e.wrap(g);a.texturePath&&(-1==b||-1!=b&&11<=b)&&(e.append('<div class="texture_over_image" />'),c(".texture_over_image",h).css({background:"url("+a.texturePath+")"}));e.after(r);var h=e.parent(".universal_video_background");a.setAsBg&&h.wrap('<div class="setAsBg" />');
r=c(".bannerControls",h);h.wrap(f);var n=h.parent(".universal_video_backgroundBorder");f=c(".bottomNav",h);a.showBottomNav||f.css("display","none");a.showOnInitBottomNav||f.css("left","-5000px");var w=c(".thumbsHolderWrapper",h),v=c(".thumbsHolderVisibleWrapper",h),k=c(".thumbsHolder",h);var t=c('<div class="carouselLeftNav"></div>');var u=c('<div class="carouselRightNav"></div>');w.append(t);w.append(u);u.css("right","0");k.css("width",t.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||w.css({opacity:0,
display:"none"});f=Math.floor(1E5*Math.random());g=c("<div></div>").addClass("lbg_player");e.append(g);var z="lbg_player"+f;c(".lbg_player",h).attr("id",z);g=c("<div></div>").addClass("lbg_vimeo_player");e.append(g);var y="lbg_vimeo_player"+f;w.css({background:a.thumbsWrapperBg});var p=0,d={current_img_no:0,currentImg:0,current_imgInside:"",is_very_first:!0,windowWidth:0,currentThumb:[],carouselStep:0,thumbMarginTop:0,thumbBorderWidth:0,thumbMarginLeft:0,bottomNavClicked:!1,haveYouTube:!1,haveVimeo:!1,
haveSelfHosted:!1,html5_video_id:"html5_video_id_"+f,bannerRatio:a.origWidth/a.origHeight,player:!1,vimeo_player:!1,vimeo_iframe:!1,show_vimeo_controls:""};a.showVideoControls||(d.show_vimeo_controls="&amp;background=1&amp;mute=0&amp;loop=0");n.width(a.width);n.height(a.height);n.css("background",a.borderColor);h.width(a.width-2*a.borderWidth/(a.origWidth/a.width));h.height(a.height-2*a.borderWidth/(a.origWidth/a.width));h.css({left:a.borderWidth/(a.origWidth/a.width)+"px",top:a.borderWidth/(a.origWidth/
a.width)+"px"});r.width("100%");var m=e.find("ul:first").children(),q,B="";m.each(function(){d.currentImg=c(this);d.currentImg.is("li")||(d.currentImg=d.currentImg.find("li:first"));d.currentImg.is("li")&&(d.currentImg.css("display","none"),p++,void 0!=c(m[p-1]).attr("data-youtube")&&""!=c(m[p-1]).attr("data-youtube")&&(d.haveYouTube=!0),void 0!=c(m[p-1]).attr("data-vimeo")&&""!=c(m[p-1]).attr("data-vimeo")&&(d.haveVimeo=!0),void 0!=c(m[p-1]).attr("data-selfhostedMP4")&&""!=c(m[p-1]).attr("data-selfhostedMP4")&&
(d.haveSelfHosted=!0),B=c(m[p-1]).attr("data-bottom-thumb"),q=c('<div class="thumbsHolder_ThumbOFF lbg_grid_tooltip" rel="'+(p-1)+'" title=""><img src="'+B+'"></div>'),q.width(a.origThumbImgW),q.height(a.origThumbImgH),k.append(q),D(a,d,q),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-t.width()-u.width())/(2*d.thumbBorderWidth+q.width()))-1),a.width100Proc&&!a.height100Proc&&(a.numberOfThumbsPerScreen-=3),a.origThumbW=q.width(),a.origThumbH=q.height(),
a.origthumbsHolderWrapperH=w.height(),d.thumbBorderWidth=q.css("borderLeftWidth").substr(0,q.css("borderLeftWidth").lastIndexOf("px")),d.thumbMarginLeft=Math.floor((a.origWidth-t.width()-u.width()-(2*d.thumbBorderWidth+q.width())*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1))),k.css("width",k.width()+d.thumbMarginLeft+(2*d.thumbBorderWidth+q.width())+"px"),parseInt((w.height()-parseInt(q.css("height").substring(0,q.css("height").length-2)))/2,10),k.css("height",k.height()+d.thumbMarginTop+
q.height()+"px"))});var x=c(".thumbsHolder_ThumbOFF",h);t.addClass("carouselLeftNavDisabled");a.numberOfThumbsPerScreen>=p?(u.addClass("carouselRightNavDisabled"),t.css("display","none"),u.css("display","none"),w.css({"border-left":parseInt(a.borderWidth/(a.origWidth/a.width),10)+"px solid "+a.borderColor,"border-right":parseInt(a.borderWidth/(a.origWidth/a.width),10)+"px solid "+a.borderColor,left:-1*parseInt(a.borderWidth/(a.origWidth/a.width),10)+"px"})):v.css("left",t.width()+"px");L(d,a,p,h,
x,k,t,u,q,v,w);d.current_img_no=a.firstImg;a.firstImg>p&&(d.current_img_no=p);0>a.firstImg&&(d.current_img_no=0);a.randomizeVideos&&(d.current_img_no=Math.floor(Math.random()*p));G(a,d,c(x[d.current_img_no]));if(d.haveYouTube){var N=function(b){b.data==YT.PlayerState.ENDED&&(1==p&&a.loop?(d.player.seekTo(0),d.player.playVideo()):E(1,d,a,p,x,h,q,k,m,y,t,u))},O=function(b){b.target.setPlaybackQuality(a.suggestedQuality);-1==l.indexOf("ipad")&&-1==l.indexOf("iphone")&&-1==l.indexOf("ipod")&&-1==l.indexOf("webos")&&
-1==navigator.userAgent.indexOf("Android")&&(d.player.setVolume(100*a.initialVolume),a.autoPlayFirstVideo?void 0!=c(m[d.current_img_no]).attr("data-youtube")&&""!=c(m[d.current_img_no]).attr("data-youtube")&&b.target.playVideo():(b.target.pauseVideo(),d.player.cueVideoById(d.currentImg.attr("data-youtube"))))};r=document.createElement("script");r.src=a.youtubeJsUrl;f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(r,f);window.onYouTubeIframeAPIReady=function(){var b=0;a.showVideoControls&&
(b=1);void 0!=c(m[d.current_img_no]).attr("data-youtube")&&""!=c(m[d.current_img_no]).attr("data-youtube")?(d.player=new YT.Player(z,{width:a.width-2*a.borderWidth,height:a.height-2*a.borderWidth,videoId:c(m[d.current_img_no]).attr("data-youtube"),playerVars:{rel:0,wmode:"transparent",controls:b,showinfo:b,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,disablekb:1},events:{onReady:O,onStateChange:N}}),c(".lbg_player",h).css({"z-index":3})):d.player=new YT.Player(z,{width:"100%",height:"100%",
videoId:"xoORbLlFsis",playerVars:{rel:0,wmode:"transparent",controls:b,showinfo:b,html5:1,modestbranding:1,cc_load_policy:0,iv_load_policy:3,disablekb:1},events:{onReady:O,onStateChange:N}})}}if(d.haveVimeo){var H=function(b){1==p&&a.loop||E(1,d,a,p,x,h,q,k,m,y,t,u)};h.css("background","#000000");void 0!=c(m[d.current_img_no]).attr("data-vimeo")&&""!=c(m[d.current_img_no]).attr("data-vimeo")?(c(".lbg_vimeo_player",h).html('<iframe id="'+y+'" src="//player.vimeo.com/video/'+c(m[d.current_img_no]).attr("data-vimeo")+
"?player_id="+y+d.show_vimeo_controls+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="autoplay; encrypted-media"></iframe>'),c(".lbg_vimeo_player",h).css({"z-index":0})):c(".lbg_vimeo_player",h).html('<iframe id="'+y+'" src="//player.vimeo.com/video/257707848?player_id='+y+d.show_vimeo_controls+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="autoplay; encrypted-media"></iframe>');
d.vimeo_iframe=c("#"+y)[0];d.vimeo_player=new Vimeo.Player(d.vimeo_iframe);d.vimeo_player.ready().then(function(){d.vimeo_player.setVolume(a.initialVolume);1==p&&a.loop&&d.vimeo_player.setLoop(!0).then(function(a){})["catch"](function(a){});1<p&&!a.showVideoControls&&d.vimeo_player.setLoop(!1).then(function(a){})["catch"](function(a){});c(".lbg_vimeo_player",h).css({"z-index":0});a.autoPlayFirstVideo?void 0!=c(m[d.current_img_no]).attr("data-vimeo")&&""!=c(m[d.current_img_no]).attr("data-vimeo")&&
-1==l.indexOf("ipad")&&-1==l.indexOf("iphone")&&-1==l.indexOf("ipod")&&-1==l.indexOf("webos")&&-1==navigator.userAgent.indexOf("Android")&&d.vimeo_player.play():d.vimeo_player.pause();d.vimeo_player.on("ended",H)})}d.haveSelfHosted&&(r="",a.showVideoControls&&(r=' controls="controls"'),f="",a.autoPlayFirstVideo&&(f=' autoplay="autoplay"'),-1!=l.indexOf("ipad")||-1!=l.indexOf("iphone")||-1!=l.indexOf("ipod")||-1!=l.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android")?a.autoPlayOnMobile&&(f=
" muted playsinline"):0===a.initialVolume&&(f+=' muted="muted"'),r=c('<video id="'+d.html5_video_id+'" width="100%" height="100%" preload="auto"'+r+f+"></video>"),h.append(r),c("#"+d.html5_video_id).css({"z-index":-1,width:0,height:0,position:"absolute",background:"#000000"}),document.getElementById(d.html5_video_id).volume=a.initialVolume,void 0!=c(m[d.current_img_no]).attr("data-selfhostedMP4")&&""!=c(m[d.current_img_no]).attr("data-selfhostedMP4")&&(document.getElementById(d.html5_video_id).src=
M(b,c(m[d.current_img_no]),d.html5_video_id),document.getElementById(d.html5_video_id).load(),c("#"+d.html5_video_id).css({"z-index":0,width:"100%",height:"100%"}),a.autoPlayFirstVideo&&document.getElementById(d.html5_video_id).play()),document.getElementById(d.html5_video_id).addEventListener("ended",function(b){1==p&&a.loop?document.getElementById(d.html5_video_id).play():E(1,d,a,p,x,h,q,k,m,y,t,u)},!1));a.width100Proc&&a.height100Proc&&a.setAsBg?I(d,a,m,h):(c(".lbg_player",h).width(h.width()),
c(".lbg_player",h).height(h.height()),c(".lbg_vimeo_player",h).width(h.width()),c(".lbg_vimeo_player",h).height(h.height()));d.current_img_no>=a.numberOfThumbsPerScreen&&A(0,k,t,u,a,p,q,d);d.currentImg=c(m[d.current_img_no]);d.current_imgInside=d.currentImg.find("img:first");x.click(function(){var b=c(this).attr("rel");D(a,d,c(x[d.current_img_no]));K(d,a,h,y);d.bottomNavClicked=!0;d.current_img_no=b-1;E(1,d,a,p,x,h,q,k,m,y,t,u)});x.mouseenter(function(){var b=c(this);b.attr("rel");G(a,d,b)});x.mouseleave(function(){var b=
c(this),e=b.attr("rel");d.current_img_no!=e&&D(a,d,b)});h.mouseenter(function(){a.autoHideBottomNav&&a.showBottomNav&&!(0>a.thumbsWrapperMarginTop&&d.isVideoPlaying)&&a.showBottomNav&&(w.css({display:"block"}),w.stop().animate({opacity:1},500,"swing",function(){}))});h.mouseleave(function(){a.autoHideBottomNav&&a.showBottomNav&&w.stop().animate({opacity:0},300,"swing",function(){})});P(a,m);var J=!1,C=!0;c(window).resize(function(){var b=F();C=!0;-1!=b&&9==b&&0==d.windowWidth&&(C=!1);d.windowWidth==
c(window).width()?(C=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,C=!0)):d.windowWidth=c(window).width();a.responsive&&C&&(!1!==J&&clearTimeout(J),J=setTimeout(function(){var b=a,g=p,f=h,l=q;F();if(b.width100Proc&&b.height100Proc&&!b.setAsBg){var r=c("body").css("overflow");c("body").css("overflow","hidden")}responsiveWidth=e.parent().parent().parent().width();responsiveHeight=e.parent().parent().parent().height();
b.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());b.width100Proc&&(b.width=responsiveWidth);b.height100Proc&&(b.height=responsiveHeight);if(b.origWidth!=responsiveWidth||b.width100Proc)b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:b.width100Proc||(b.width=b.origWidth),b.height100Proc||(b.height=b.width/d.bannerRatio),b.width=parseInt(b.width,10),b.height=parseInt(b.height,10),n.width(b.width),n.height(b.height),f.width(parseInt(b.width-
2*b.borderWidth/(b.origWidth/b.width),10)),f.height(parseInt(b.height-2*b.borderWidth/(b.origWidth/b.width),10)),f.css({left:b.borderWidth/(b.origWidth/b.width)+"px",top:b.borderWidth/(b.origWidth/b.width)+"px"}),b.width100Proc&&b.height100Proc&&b.setAsBg?I(d,b,m,f):(c(".lbg_player",f).width(f.width()),c(".lbg_player",f).height(f.height()),c(".lbg_vimeo_player",f).width(f.width()),c(".lbg_vimeo_player",f).height(f.height())),L(d,b,g,f,x,k,t,u,l,v,w);A(0,k,t,u,b,g,l,d);b.width100Proc&&b.height100Proc&&
!b.setAsBg&&c("body").css("overflow",r)},300))});t.click(function(){d.isCarouselScrolling||(currentCarouselLeft=k.css("left").substr(0,k.css("left").lastIndexOf("px")),0>currentCarouselLeft&&A(1,k,t,u,a,p,q,d))});u.click(function(){d.isCarouselScrolling||(currentCarouselLeft=k.css("left").substr(0,k.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-d.carouselStep)<(2*d.thumbBorderWidth+q.width()+d.thumbMarginLeft)*p&&A(-1,k,t,u,a,p,q,d))})})};c.fn.universal_video_background.defaults={skin:"thumbs",
width:960,height:540,width100Proc:!1,height100Proc:!1,randomizeVideos:!1,firstImg:0,initialVolume:1,loop:!0,setAsBg:!1,texturePath:"",borderWidth:0,borderColor:"#FFFFFF",absUrl:"",responsive:!0,responsiveRelativeToBrowser:!0,numberOfThumbsPerScreen:0,bottomNavPos:"center",bottomNavLateralMargin:0,thumbsWrapperMinHeight:25,thumbsWrapperMarginTop:-85,thumbsWrapperTopPadding:10,thumbsWrapperBottomPadding:10,thumbsWrapperBg:"transparent",thumbsBorderColorON:"#000000",thumbsBorderColorOFF:"#7a7a7a",thumbsBgOffColor:"#000000",
thumbsBgOffImgOpacity:100,thumbsBgOnColor:"#cc181e",thumbsBgOnImgOpacity:100,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!1,showVideoControls:!0,suggestedQuality:"default",autoPlayFirstVideo:!0,autoPlayOnMobile:!1,showTooltip:!1,youtubeJsUrl:"https://www.youtube.com/iframe_api",vimeoJsUrl:"http://a.vimeocdn.com/js/froogaloop2.min.js",videoProportionWidth:16,videoProportionHeight:9,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origThumbImgW:110,origThumbImgH:65,origthumbLeftPadding:0,
origthumbRightPadding:0,origthumbTopPadding:0,origthumbBottomPadding:0,origthumbTitleFont:0,origthumbRegFont:0,origthumbTitleLineHeight:0,origthumbRegLineHeight:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
